/*
 Highcharts 4.0.4 JS v/Highstock 2.0.4 (2014-09-02)

 Standalone Highcharts Framework

 License: MIT License
 Highcharts 4.0.4 JS v/Highstock 2.0.4 (2014-09-02)

 (c) 2009-2014 Torstein Honsi

 License: www.highcharts.com/license
 */
var HighchartsAdapter=function(){function t(p){function q(n,l,m){n.removeEventListener(l,m,!1)}function n(n,l,m){m=n.HCProxiedMethods[m.toString()];n.detachEvent("on"+l,m)}function m(m,l){var p=m.HCEvents,t,u,y;if(m.removeEventListener)t=q;else if(m.attachEvent)t=n;else return;l?(u={},u[l]=!0):u=p;for(y in u)if(p[y])for(u=p[y].length;u--;)t(m,y,p[y][u])}p.HCExtended||Highcharts.extend(p,{HCExtended:!0,HCEvents:{},bind:function(n,l){var m=this,q=this.HCEvents,p;m.addEventListener?m.addEventListener(n,
    l,!1):m.attachEvent&&(p=function(n){n.target=n.srcElement||window;l.call(m,n)},m.HCProxiedMethods||(m.HCProxiedMethods={}),m.HCProxiedMethods[l.toString()]=p,m.attachEvent("on"+n,p));q[n]===y&&(q[n]=[]);q[n].push(l)},unbind:function(p,l){var t,u;p?(t=this.HCEvents[p]||[],l?(u=HighchartsAdapter.inArray(l,t),-1<u&&(t.splice(u,1),this.HCEvents[p]=t),this.removeEventListener?q(this,p,l):this.attachEvent&&n(this,p,l)):(m(this,p),this.HCEvents[p]=[])):(m(this),this.HCEvents={})},trigger:function(n,l){var m=
    this.HCEvents[n]||[],q=m.length,p,t,u;t=function(){l.defaultPrevented=!0};for(p=0;p<q;p++){u=m[p];if(l.stopped)break;l.preventDefault=t;l.target=this;l.type||(l.type=n);!1===u.call(this,l)&&l.preventDefault()}}});return p}var y,u=document,X=[],C=[],ba,P={},fa;Math.easeInOutSine=function(p,q,n,m){return-n/2*(Math.cos(Math.PI*p/m)-1)+q};return{init:function(p){u.defaultView||(this._getStyle=function(q,n){var m;if(q.style[n])return q.style[n];"opacity"===n&&(n="filter");m=q.currentStyle[n.replace(/\-(\w)/g,
    function(n,l){return l.toUpperCase()})];"filter"===n&&(m=m.replace(/alpha\(opacity=([0-9]+)\)/,function(n,l){return l/100}));return""===m?1:m},this.adapterRun=function(q,n){var m={width:"clientWidth",height:"clientHeight"}[n];if(m)return q.style.zoom=1,q[m]-2*parseInt(HighchartsAdapter._getStyle(q,"padding"),10)});Array.prototype.forEach||(this.each=function(q,n){for(var m=0,p=q.length;m<p;m++)if(!1===n.call(q[m],q[m],m,q))return m});Array.prototype.indexOf||(this.inArray=function(q,n){var m,p=0;
    if(n)for(m=n.length;p<m;p++)if(n[p]===q)return p;return-1});Array.prototype.filter||(this.grep=function(q,n){for(var m=[],p=0,l=q.length;p<l;p++)n(q[p],p)&&m.push(q[p]);return m});fa=function(p,n,m){this.options=n;this.elem=p;this.prop=m};fa.prototype={update:function(){var q;q=this.paths;var n=this.elem,m=n.element;if(P[this.prop])P[this.prop](this);else q&&m?n.attr("d",p.step(q[0],q[1],this.now,this.toD)):n.attr?m&&n.attr(this.prop,this.now):(q={},q[this.prop]=this.now+this.unit,Highcharts.css(n,
    q));this.options.step&&this.options.step.call(this.elem,this.now,this)},custom:function(p,n,m){var t=this,l=function(l){return t.step(l)},u;this.startTime=+new Date;this.start=p;this.end=n;this.unit=m;this.now=this.start;this.pos=this.state=0;l.elem=this.elem;l()&&1===C.push(l)&&(ba=setInterval(function(){for(u=0;u<C.length;u++)C[u]()||C.splice(u--,1);C.length||clearInterval(ba)},13))},step:function(p){var n=+new Date,m;m=this.options;var t=this.elem,l;if(t.stopAnimation||t.attr&&!t.element)m=!1;
else if(p||n>=m.duration+this.startTime){this.now=this.end;this.pos=this.state=1;this.update();p=this.options.curAnim[this.prop]=!0;for(l in m.curAnim)!0!==m.curAnim[l]&&(p=!1);p&&m.complete&&m.complete.call(t);m=!1}else t=n-this.startTime,this.state=t/m.duration,this.pos=m.easing(t,0,1,m.duration),this.now=this.start+(this.end-this.start)*this.pos,this.update(),m=!0;return m}};this.animate=function(q,n,m){var t,l="",u,y,C;q.stopAnimation=!1;if("object"!==typeof m||null===m)t=arguments,m={duration:t[2],
    easing:t[3],complete:t[4]};"number"!==typeof m.duration&&(m.duration=400);m.easing=Math[m.easing]||Math.easeInOutSine;m.curAnim=Highcharts.extend({},n);for(C in n)y=new fa(q,m,C),u=null,"d"===C?(y.paths=p.init(q,q.d,n.d),y.toD=n.d,t=0,u=1):q.attr?t=q.attr(C):(t=parseFloat(HighchartsAdapter._getStyle(q,C))||0,"opacity"!==C&&(l="px")),u||(u=n[C]),y.custom(t,u,l)}},_getStyle:function(p,q){return window.getComputedStyle(p,void 0).getPropertyValue(q)},addAnimSetter:function(p,q){P[p]=q},getScript:function(p,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              q){var n=u.getElementsByTagName("head")[0],m=u.createElement("script");m.type="text/javascript";m.src=p;m.onload=q;n.appendChild(m)},inArray:function(p,q){return q.indexOf?q.indexOf(p):X.indexOf.call(q,p)},adapterRun:function(p,q){return parseInt(HighchartsAdapter._getStyle(p,q),10)},grep:function(p,q){return X.filter.call(p,q)},map:function(p,q){for(var n=[],m=0,t=p.length;m<t;m++)n[m]=q.call(p[m],p[m],m,p);return n},offset:function(p){var q=document.documentElement;p=p.getBoundingClientRect();return{top:p.top+
    (window.pageYOffset||q.scrollTop)-(q.clientTop||0),left:p.left+(window.pageXOffset||q.scrollLeft)-(q.clientLeft||0)}},addEvent:function(p,q,n){t(p).bind(q,n)},removeEvent:function(p,q,n){t(p).unbind(q,n)},fireEvent:function(p,q,n,m){var t;u.createEvent&&(p.dispatchEvent||p.fireEvent)?(t=u.createEvent("Events"),t.initEvent(q,!0,!0),t.target=p,Highcharts.extend(t,n),p.dispatchEvent?p.dispatchEvent(t):p.fireEvent(q,t)):!0===p.HCExtended&&(n=n||{},p.trigger(q,n));n&&n.defaultPrevented&&(m=null);m&&m(n)},
    washMouseEvent:function(p){return p},stop:function(p){p.stopAnimation=!0},each:function(p,q){return Array.prototype.forEach.call(p,q)}}}();
(function(){function t(a,b){var c;a||(a={});for(c in b)a[c]=b[c];return a}function y(){var a,b=arguments,c,d={},e=function(a,b){var c,d;"object"!==typeof a&&(a={});for(d in b)b.hasOwnProperty(d)&&((c=b[d])&&"object"===typeof c&&"[object Array]"!==Object.prototype.toString.call(c)&&"renderTo"!==d&&"number"!==typeof c.nodeType?a[d]=e(a[d]||{},c):a[d]=b[d]);return a};!0===b[0]&&(d=b[1],b=Array.prototype.slice.call(b,2));c=b.length;for(a=0;a<c;a++)d=e(d,b[a]);return d}function u(a,b){return parseInt(a,
        b||10)}function X(a){return"string"===typeof a}function C(a){return a&&"object"===typeof a}function ba(a){return"[object Array]"===Object.prototype.toString.call(a)}function P(a){return"number"===typeof a}function fa(a){return H.log(a)/H.LN10}function p(a){return H.pow(10,a)}function q(a,b){for(var c=a.length;c--;)if(a[c]===b){a.splice(c,1);break}}function n(a){return a!==A&&null!==a}function m(a,b,c){var d,e;if(X(b))n(c)?a.setAttribute(b,c):a&&a.getAttribute&&(e=a.getAttribute(b));else if(n(b)&&
    C(b))for(d in b)a.setAttribute(d,b[d]);return e}function pa(a){return ba(a)?a:[a]}function l(){var a=arguments,b,c,d=a.length;for(b=0;b<d;b++)if(c=a[b],c!==A&&null!==c)return c}function R(a,b){ia&&!S&&b&&b.opacity!==A&&(b.filter="alpha(opacity="+100*b.opacity+")");t(a.style,b)}function qa(a,b,c,d,e){a=E.createElement(a);b&&t(a,b);e&&R(a,{padding:0,border:"none",margin:0});c&&R(a,c);d&&d.appendChild(a);return a}function ab(a,b){var c=function(){return A};c.prototype=new a;t(c.prototype,b);return c}
    function aa(a,b,c,d){var e=ca.numberFormat,f=F.lang,g=+a||0,h=-1===b?(g.toString().split(".")[1]||"").length:isNaN(b=Y(b))?2:b,k=void 0===c?f.decimalPoint:c,f=void 0===d?f.thousandsSep:d,r=0>g?"-":"",w=String(u(g=Y(g).toFixed(h))),D=3<w.length?w.length%3:0;return e!==aa?e(a,b,c,d):r+(D?w.substr(0,D)+f:"")+w.substr(D).replace(/(\d{3})(?=\d)/g,"$1"+f)+(h?k+Y(g-w).toFixed(h).slice(2):"")}function ea(a,b){return Array((b||2)+1-String(a).length).join(0)+a}function bb(a,b,c){var d=a[b];a[b]=function(){var a=
        Array.prototype.slice.call(arguments);a.unshift(d);return c.apply(this,a)}}function xa(a,b){for(var c="{",d=!1,e,f,g,h,k,r=[];-1!==(c=a.indexOf(c));){e=a.slice(0,c);if(d){f=e.split(":");g=f.shift().split(".");k=g.length;e=b;for(h=0;h<k;h++)e=e[g[h]];f.length&&(f=f.join(":"),g=/\.([0-9])/,h=F.lang,k=void 0,/f$/.test(f)?(k=(k=f.match(g))?k[1]:-1,null!==e&&(e=aa(e,k,h.decimalPoint,-1<f.indexOf(",")?h.thousandsSep:""))):e=ya(f,e))}r.push(e);a=a.slice(c+1);c=(d=!d)?"}":"{"}r.push(a);return r.join("")}
    function cb(a,b,c,d){var e;c=l(c,1);e=a/c;b||(b=[1,2,2.5,5,10],!1===d&&(1===c?b=[1,2,5,10]:.1>=c&&(b=[1/c])));for(d=0;d<b.length&&!(a=b[d],e<=(b[d]+(b[d+1]||b[d]))/2);d++);return a*c}function La(a,b){var c=a.length,d,e;for(e=0;e<c;e++)a[e].ss_i=e;a.sort(function(a,c){d=b(a,c);return 0===d?a.ss_i-c.ss_i:d});for(e=0;e<c;e++)delete a[e].ss_i}function za(a){for(var b=a.length,c=a[0];b--;)a[b]<c&&(c=a[b]);return c}function ra(a){for(var b=a.length,c=a[0];b--;)a[b]>c&&(c=a[b]);return c}function Aa(a,b){for(var c in a)a[c]&&
        a[c]!==b&&a[c].destroy&&a[c].destroy(),delete a[c]}function Ba(a){Ca||(Ca=qa("div"));a&&Ca.appendChild(a);Ca.innerHTML=""}function Z(a){return parseFloat(a.toPrecision(14))}function db(){var a=F.global.useUTC,b=a?"getUTC":"get",c=a?"setUTC":"set";ja=F.global.Date||window.Date;ka=6E4*(a&&F.global.timezoneOffset||0);Da=a?ja.UTC:function(a,b,c,g,h,k){return(new ja(a,b,l(c,1),l(g,0),l(h,0),l(k,0))).getTime()};Ma=b+"Minutes";Na=b+"Hours";Oa=b+"Day";sa=b+"Date";Ea=b+"Month";Fa=b+"FullYear";eb=c+"Minutes";
        fb=c+"Hours";Pa=c+"Date";gb=c+"Month";hb=c+"FullYear"}function L(){}function la(a,b,c,d){this.axis=a;this.pos=b;this.type=c||"";this.isNew=!0;c||d||this.addLabel()}function ma(){this.init.apply(this,arguments)}function Qa(){this.init.apply(this,arguments)}var A,E=document,J=window,H=Math,B=H.round,I=H.floor,na=H.ceil,x=H.max,V=H.min,Y=H.abs,ta=H.cos,Ga=H.sin,ib=H.PI,jb=2*ib/360,ga=navigator.userAgent,rb=J.opera,ia=/msie/i.test(ga)&&!rb,sb=/AppleWebKit/.test(ga),Ha=/Firefox/.test(ga),kb=/(Mobile|Android|Windows Phone)/.test(ga),
        S=!!E.createElementNS&&!!E.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect,tb=Ha&&4>parseInt(ga.split("Firefox/")[1],10),$=!S&&!ia&&!!E.createElement("canvas").getContext,lb={},Ra=0,Ca,F,ya,T,Sa,z,Q,ha=[],mb=0,ub=/^[0-9]+$/,ja,Da,ka,Ma,Na,Oa,sa,Ea,Fa,eb,fb,Pa,gb,hb,ua={},ca;J.Highcharts?Q(16,!0):ca=J.Highcharts={};ya=function(a,b,c){if(!n(b)||isNaN(b))return"Invalid date";a=l(a,"%Y-%m-%d %H:%M:%S");var d=new ja(b-ka),e,f=d[Na](),g=d[Oa](),h=d[sa](),k=d[Ea](),r=d[Fa](),w=F.lang,D=
        w.weekdays,d=t({a:D[g].substr(0,3),A:D[g],d:ea(h),e:h,b:w.shortMonths[k],B:w.months[k],m:ea(k+1),y:r.toString().substr(2,2),Y:r,H:ea(f),I:ea(f%12||12),l:f%12||12,M:ea(d[Ma]()),p:12>f?"AM":"PM",P:12>f?"am":"pm",S:ea(d.getSeconds()),L:ea(B(b%1E3),3)},ca.dateFormats);for(e in d)for(;-1!==a.indexOf("%"+e);)a=a.replace("%"+e,"function"===typeof d[e]?d[e](b):d[e]);return c?a.substr(0,1).toUpperCase()+a.substr(1):a};Q=function(a,b){var c="Highcharts error #"+a+": www.highcharts.com/errors/"+a;if(b)throw c;
        J.console&&console.log(c)};z={millisecond:1,second:1E3,minute:6E4,hour:36E5,day:864E5,week:6048E5,month:26784E5,year:31556952E3};Sa={init:function(a,b,c){b=b||"";var d=a.shift,e=-1<b.indexOf("C"),f=e?7:3,g;b=b.split(" ");c=[].concat(c);var h,k,r=function(a){for(g=a.length;g--;)"M"===a[g]&&a.splice(g+1,0,a[g+1],a[g+2],a[g+1],a[g+2])};e&&(r(b),r(c));a.isArea&&(h=b.splice(b.length-6,6),k=c.splice(c.length-6,6));if(d<=c.length/f&&b.length===c.length)for(;d--;)c=[].concat(c).splice(0,f).concat(c);a.shift=
        0;if(b.length)for(a=c.length;b.length<a;)d=[].concat(b).splice(b.length-f,f),e&&(d[f-6]=d[f-2],d[f-5]=d[f-1]),b=b.concat(d);h&&(b=b.concat(h),c=c.concat(k));return[b,c]},step:function(a,b,c,d){var e=[],f=a.length;if(1===c)e=d;else if(f===b.length&&1>c)for(;f--;)d=parseFloat(a[f]),e[f]=isNaN(d)?a[f]:c*parseFloat(b[f]-d)+d;else e=b;return e}};var Ia=J.HighchartsAdapter,W=Ia||{};Ia&&Ia.init.call(Ia,Sa);var Ja=W.adapterRun,vb=W.inArray,v=W.each,Ta=W.grep,nb=W.map,N=W.addEvent,U=W.removeEvent,O=W.fireEvent,
        ob=W.animate,Ua=W.stop,Va={enabled:!0,x:0,y:15,style:{color:"#606060",cursor:"default",fontSize:"11px"}};F={colors:"#7cb5ec #434348 #90ed7d #f7a35c #8085e9 #f15c80 #e4d354 #8085e8 #8d4653 #91e8e1".split(" "),symbols:["circle","diamond","square","triangle","triangle-down"],lang:{loading:"Loading...",months:"January February March April May June July August September October November December".split(" "),shortMonths:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),weekdays:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
        decimalPoint:".",numericSymbols:"kMGTPE".split(""),resetZoom:"Reset zoom",resetZoomTitle:"Reset zoom level 1:1",thousandsSep:","},global:{useUTC:!0,canvasToolsURL:"http://code.highcharts.com@product.cdnpath@//Highstock 2.0.4/modules/canvas-tools.js",VMLRadialGradientURL:"http://code.highcharts.com@product.cdnpath@//Highstock 2.0.4/gfx/vml-radial-gradient.png"},chart:{borderColor:"#4572A7",borderRadius:0,defaultSeriesType:"line",ignoreHiddenSeries:!0,spacing:[10,10,15,10],backgroundColor:"#FFFFFF",
        plotBorderColor:"#C0C0C0",resetZoomButton:{theme:{zIndex:20},position:{align:"right",x:-10,y:10}}},title:{text:"Chart title",align:"center",margin:15,style:{color:"#333333",fontSize:"18px"}},subtitle:{text:"",align:"center",style:{color:"#555555"}},plotOptions:{line:{allowPointSelect:!1,showCheckbox:!1,animation:{duration:1E3},events:{},lineWidth:2,marker:{lineWidth:0,radius:4,lineColor:"#FFFFFF",states:{hover:{enabled:!0,lineWidthPlus:1,radiusPlus:2},select:{fillColor:"#FFFFFF",lineColor:"#000000",
        lineWidth:2}}},point:{events:{}},dataLabels:y(Va,{align:"center",enabled:!1,formatter:function(){return null===this.y?"":aa(this.y,-1)},verticalAlign:"bottom",y:0}),cropThreshold:300,pointRange:0,states:{hover:{lineWidthPlus:1,marker:{},halo:{size:10,opacity:.25}},select:{marker:{}}},stickyTracking:!0,turboThreshold:1E3}},labels:{style:{position:"absolute",color:"#3E576F"}},legend:{enabled:!0,align:"center",layout:"horizontal",labelFormatter:function(){return this.name},borderColor:"#909090",borderRadius:0,
        navigation:{activeColor:"#274b6d",inactiveColor:"#CCC"},shadow:!1,itemStyle:{color:"#333333",fontSize:"12px",fontWeight:"bold"},itemHoverStyle:{color:"#000"},itemHiddenStyle:{color:"#CCC"},itemCheckboxStyle:{position:"absolute",width:"13px",height:"13px"},symbolPadding:5,verticalAlign:"bottom",x:0,y:0,title:{style:{fontWeight:"bold"}}},loading:{labelStyle:{fontWeight:"bold",position:"relative",top:"45%"},style:{position:"absolute",backgroundColor:"white",opacity:.5,textAlign:"center"}},tooltip:{enabled:!0,
        animation:S,backgroundColor:"rgba(249, 249, 249, .85)",borderWidth:1,borderRadius:3,dateTimeLabelFormats:{millisecond:"%A, %b %e, %H:%M:%S.%L",second:"%A, %b %e, %H:%M:%S",minute:"%A, %b %e, %H:%M",hour:"%A, %b %e, %H:%M",day:"%A, %b %e, %Y",week:"Week from %A, %b %e, %Y",month:"%B %Y",year:"%Y"},headerFormat:'<span style="font-size: 10px">{point.key}</span><br/>',pointFormat:'<span style="color:{series.color}">\u25cf</span> {series.name}: <b>{point.y}</b><br/>',shadow:!0,snap:kb?25:10,style:{color:"#333333",
            cursor:"default",fontSize:"12px",padding:"8px",whiteSpace:"nowrap"}},credits:{enabled:!0,text:"Highcharts.com",href:"http://www.highcharts.com",position:{align:"right",x:-10,verticalAlign:"bottom",y:-5},style:{cursor:"pointer",color:"#909090",fontSize:"9px"}}};var Wa=F.plotOptions;db();var wb=/rgba\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]?(?:\.[0-9]+)?)\s*\)/,xb=/#([a-fA-F0-9]{2})([a-fA-F0-9]{2})([a-fA-F0-9]{2})/,yb=/rgb\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*\)/,
        va=function(a){var b=[],c,d;(function(a){a&&a.stops?d=nb(a.stops,function(a){return va(a[1])}):(c=wb.exec(a))?b=[u(c[1]),u(c[2]),u(c[3]),parseFloat(c[4],10)]:(c=xb.exec(a))?b=[u(c[1],16),u(c[2],16),u(c[3],16),1]:(c=yb.exec(a))&&(b=[u(c[1]),u(c[2]),u(c[3]),1])})(a);return{get:function(c){var f;d?(f=y(a),f.stops=[].concat(f.stops),v(d,function(a,b){f.stops[b]=[f.stops[b][0],a.get(c)]})):f=b&&!isNaN(b[0])?"rgb"===c?"rgb("+b[0]+","+b[1]+","+b[2]+")":"a"===c?b[3]:"rgba("+b.join(",")+")":a;return f},brighten:function(a){if(d)v(d,
            function(b){b.brighten(a)});else if(P(a)&&0!==a){var c;for(c=0;3>c;c++)b[c]+=u(255*a),0>b[c]&&(b[c]=0),255<b[c]&&(b[c]=255)}return this},rgba:b,setOpacity:function(a){b[3]=a;return this}}};L.prototype={opacity:1,textProps:"fontSize fontWeight fontFamily color lineHeight width textDecoration textShadow HcTextStroke".split(" "),init:function(a,b){this.element="span"===b?qa(b):E.createElementNS("http://www.w3.org/2000/svg",b);this.renderer=a},animate:function(a,b,c){b=l(b,T,!0);Ua(this);b?(b=y(b,{}),
        c&&(b.complete=c),ob(this,a,b)):(this.attr(a),c&&c());return this},colorGradient:function(a,b,c){var d=this.renderer,e,f,g,h,k,r,w,D,G,s,l=[];a.linearGradient?f="linearGradient":a.radialGradient&&(f="radialGradient");if(f){g=a[f];h=d.gradients;r=a.stops;G=c.radialReference;ba(g)&&(a[f]=g={x1:g[0],y1:g[1],x2:g[2],y2:g[3],gradientUnits:"userSpaceOnUse"});"radialGradient"===f&&G&&!n(g.gradientUnits)&&(g=y(g,{cx:G[0]-G[2]/2+g.cx*G[2],cy:G[1]-G[2]/2+g.cy*G[2],r:g.r*G[2],gradientUnits:"userSpaceOnUse"}));
        for(s in g)"id"!==s&&l.push(s,g[s]);for(s in r)l.push(r[s]);l=l.join(",");h[l]?a=h[l].attr("id"):(g.id=a="highcharts-"+Ra++,h[l]=k=d.createElement(f).attr(g).add(d.defs),k.stops=[],v(r,function(a){0===a[1].indexOf("rgba")?(e=va(a[1]),w=e.get("rgb"),D=e.get("a")):(w=a[1],D=1);a=d.createElement("stop").attr({offset:a[0],"stop-color":w,"stop-opacity":D}).add(k);k.stops.push(a)}));c.setAttribute(b,"url("+d.url+"#"+a+")")}},attr:function(a,b){var c,d,e=this.element,f,g=this,h;"string"===typeof a&&b!==
        A&&(c=a,a={},a[c]=b);if("string"===typeof a)g=(this[a+"Getter"]||this._defaultGetter).call(this,a,e);else{for(c in a)d=a[c],h=!1,this.symbolName&&/^(x|y|width|height|r|start|end|innerR|anchorX|anchorY)/.test(c)&&(f||(this.symbolAttr(a),f=!0),h=!0),!this.rotation||"x"!==c&&"y"!==c||(this.doTransform=!0),h||(this[c+"Setter"]||this._defaultSetter).call(this,d,c,e),this.shadows&&/^(width|height|visibility|x|y|d|transform|cx|cy|r)$/.test(c)&&this.updateShadows(c,d);this.doTransform&&(this.updateTransform(),
        this.doTransform=!1)}return g},updateShadows:function(a,b){for(var c=this.shadows,d=c.length;d--;)c[d].setAttribute(a,"height"===a?x(b-(c[d].cutHeight||0),0):"d"===a?this.d:b)},addClass:function(a){var b=this.element,c=m(b,"class")||"";-1===c.indexOf(a)&&m(b,"class",c+" "+a);return this},symbolAttr:function(a){var b=this;v("x y r start end width height innerR anchorX anchorY".split(" "),function(c){b[c]=l(a[c],b[c])});b.attr({d:b.renderer.symbols[b.symbolName](b.x,b.y,b.width,b.height,b)})},clip:function(a){return this.attr("clip-path",
        a?"url("+this.renderer.url+"#"+a.id+")":"none")},crisp:function(a){var b,c={},d,e=a.strokeWidth||this.strokeWidth||0;d=B(e)%2/2;a.x=I(a.x||this.x||0)+d;a.y=I(a.y||this.y||0)+d;a.width=I((a.width||this.width||0)-2*d);a.height=I((a.height||this.height||0)-2*d);a.strokeWidth=e;for(b in a)this[b]!==a[b]&&(this[b]=c[b]=a[b]);return c},css:function(a){var b=this.styles,c={},d=this.element,e,f,g="";e=!b;a&&a.color&&(a.fill=a.color);if(b)for(f in a)a[f]!==b[f]&&(c[f]=a[f],e=!0);if(e){e=this.textWidth=a&&
        a.width&&"text"===d.nodeName.toLowerCase()&&u(a.width);b&&(a=t(b,c));this.styles=a;e&&($||!S&&this.renderer.forExport)&&delete a.width;if(ia&&!S)R(this.element,a);else{b=function(a,b){return"-"+b.toLowerCase()};for(f in a)g+=f.replace(/([A-Z])/g,b)+":"+a[f]+";";m(d,"style",g)}e&&this.added&&this.renderer.buildText(this)}return this},on:function(a,b){this.element["on"+a]=b;return this},setRadialReference:function(a){this.element.radialReference=a;return this},translate:function(a,b){return this.attr({translateX:a,
        translateY:b})},invert:function(){this.inverted=!0;this.updateTransform();return this},updateTransform:function(){var a=this.translateX||0,b=this.translateY||0,c=this.scaleX,d=this.scaleY,e=this.inverted,f=this.rotation,g=this.element;e&&(a+=this.attr("width"),b+=this.attr("height"));a=["translate("+a+","+b+")"];e?a.push("rotate(90) scale(-1,1)"):f&&a.push("rotate("+f+" "+(g.getAttribute("x")||0)+" "+(g.getAttribute("y")||0)+")");(n(c)||n(d))&&a.push("scale("+l(c,1)+" "+l(d,1)+")");a.length&&g.setAttribute("transform",
        a.join(" "))},toFront:function(){var a=this.element;a.parentNode.appendChild(a);return this},align:function(a,b,c){var d,e,f,g,h={};e=this.renderer;f=e.alignedObjects;if(a){if(this.alignOptions=a,this.alignByTranslate=b,!c||X(c))this.alignTo=d=c||"renderer",q(f,this),f.push(this),c=null}else a=this.alignOptions,b=this.alignByTranslate,d=this.alignTo;c=l(c,e[d],e);d=a.align;e=a.verticalAlign;f=(c.x||0)+(a.x||0);g=(c.y||0)+(a.y||0);if("right"===d||"center"===d)f+=(c.width-(a.width||0))/{right:1,center:2}[d];
        h[b?"translateX":"x"]=B(f);if("bottom"===e||"middle"===e)g+=(c.height-(a.height||0))/({bottom:1,middle:2}[e]||1);h[b?"translateY":"y"]=B(g);this[this.placed?"animate":"attr"](h);this.placed=!0;this.alignAttr=h;return this},getBBox:function(){var a=this.bBox,b=this.renderer,c,d,e=this.rotation;c=this.element;var f=this.styles,g=e*jb;d=this.textStr;var h;if(""===d||ub.test(d))h="num."+d.toString().length+(f?"|"+f.fontSize+"|"+f.fontFamily:"");h&&(a=b.cache[h]);if(!a){if("http://www.w3.org/2000/svg"===
        c.namespaceURI||b.forExport){try{a=c.getBBox?t({},c.getBBox()):{width:c.offsetWidth,height:c.offsetHeight}}catch(k){}if(!a||0>a.width)a={width:0,height:0}}else a=this.htmlGetBBox();b.isSVG&&(c=a.width,d=a.height,ia&&f&&"11px"===f.fontSize&&"16.9"===d.toPrecision(3)&&(a.height=d=14),e&&(a.width=Y(d*Ga(g))+Y(c*ta(g)),a.height=Y(d*ta(g))+Y(c*Ga(g))));this.bBox=a;h&&(b.cache[h]=a)}return a},show:function(a){a&&"http://www.w3.org/2000/svg"===this.element.namespaceURI?this.element.removeAttribute("visibility"):
        this.attr({visibility:a?"inherit":"visible"});return this},hide:function(){return this.attr({visibility:"hidden"})},fadeOut:function(a){var b=this;b.animate({opacity:0},{duration:a||150,complete:function(){b.attr({y:-9999})}})},add:function(a){var b=this.renderer,c=a||b,d=c.element||b.box,e=this.element,f=this.zIndex,g,h;a&&(this.parentGroup=a);this.parentInverted=a&&a.inverted;void 0!==this.textStr&&b.buildText(this);f&&(c.handleZ=!0,f=u(f));if(c.handleZ)for(a=d.childNodes,g=0;g<a.length;g++)if(b=
        a[g],c=m(b,"zIndex"),b!==e&&(u(c)>f||!n(f)&&n(c))){d.insertBefore(e,b);h=!0;break}h||d.appendChild(e);this.added=!0;if(this.onAdd)this.onAdd();return this},safeRemoveChild:function(a){var b=a.parentNode;b&&b.removeChild(a)},destroy:function(){var a=this,b=a.element||{},c=a.shadows,d=a.renderer.isSVG&&"SPAN"===b.nodeName&&a.parentGroup,e,f;b.onclick=b.onmouseout=b.onmouseover=b.onmousemove=b.point=null;Ua(a);a.clipPath&&(a.clipPath=a.clipPath.destroy());if(a.stops){for(f=0;f<a.stops.length;f++)a.stops[f]=
        a.stops[f].destroy();a.stops=null}a.safeRemoveChild(b);for(c&&v(c,function(b){a.safeRemoveChild(b)});d&&d.div&&0===d.div.childNodes.length;)b=d.parentGroup,a.safeRemoveChild(d.div),delete d.div,d=b;a.alignTo&&q(a.renderer.alignedObjects,a);for(e in a)delete a[e];return null},shadow:function(a,b,c){var d=[],e,f,g=this.element,h,k,r,w;if(a){k=l(a.width,3);r=(a.opacity||.15)/k;w=this.parentInverted?"(-1,-1)":"("+l(a.offsetX,1)+", "+l(a.offsetY,1)+")";for(e=1;e<=k;e++)f=g.cloneNode(0),h=2*k+1-2*e,m(f,
        {isShadow:"true",stroke:a.color||"black","stroke-opacity":r*e,"stroke-width":h,transform:"translate"+w,fill:"none"}),c&&(m(f,"height",x(m(f,"height")-h,0)),f.cutHeight=h),b?b.element.appendChild(f):g.parentNode.insertBefore(f,g),d.push(f);this.shadows=d}return this},xGetter:function(a){"circle"===this.element.nodeName&&(a={x:"cx",y:"cy"}[a]||a);return this._defaultGetter(a)},_defaultGetter:function(a){a=l(this[a],this.element?this.element.getAttribute(a):null,0);/^[\-0-9\.]+$/.test(a)&&(a=parseFloat(a));
        return a},dSetter:function(a,b,c){a&&a.join&&(a=a.join(" "));/(NaN| {2}|^$)/.test(a)&&(a="M 0 0");c.setAttribute(b,a);this[b]=a},dashstyleSetter:function(a){var b;if(a=a&&a.toLowerCase()){a=a.replace("shortdashdotdot","3,1,1,1,1,1,").replace("shortdashdot","3,1,1,1").replace("shortdot","1,1,").replace("shortdash","3,1,").replace("longdash","8,3,").replace(/dot/g,"1,3,").replace("dash","4,3,").replace(/,$/,"").split(",");for(b=a.length;b--;)a[b]=u(a[b])*this["stroke-width"];a=a.join(",").replace("NaN",
        "none");this.element.setAttribute("stroke-dasharray",a)}},alignSetter:function(a){this.element.setAttribute("text-anchor",{left:"start",center:"middle",right:"end"}[a])},opacitySetter:function(a,b,c){this[b]=a;c.setAttribute(b,a)},titleSetter:function(a){var b=this.element.getElementsByTagName("title")[0];b||(b=E.createElementNS("http://www.w3.org/2000/svg","title"),this.element.appendChild(b));b.textContent=l(a,"").replace(/<[^>]*>/g,"")},textSetter:function(a){a!==this.textStr&&(delete this.bBox,
        this.textStr=a,this.added&&this.renderer.buildText(this))},fillSetter:function(a,b,c){"string"===typeof a?c.setAttribute(b,a):a&&this.colorGradient(a,b,c)},zIndexSetter:function(a,b,c){c.setAttribute(b,a);this[b]=a},_defaultSetter:function(a,b,c){c.setAttribute(b,a)}};L.prototype.yGetter=L.prototype.xGetter;L.prototype.translateXSetter=L.prototype.translateYSetter=L.prototype.rotationSetter=L.prototype.verticalAlignSetter=L.prototype.scaleXSetter=L.prototype.scaleYSetter=function(a,b){this[b]=a;this.doTransform=
        !0};L.prototype["stroke-widthSetter"]=L.prototype.strokeSetter=function(a,b,c){this[b]=a;this.stroke&&this["stroke-width"]?(this.strokeWidth=this["stroke-width"],L.prototype.fillSetter.call(this,this.stroke,"stroke",c),c.setAttribute("stroke-width",this["stroke-width"]),this.hasStroke=!0):"stroke-width"===b&&0===a&&this.hasStroke&&(c.removeAttribute("stroke"),this.hasStroke=!1)};var wa=function(){this.init.apply(this,arguments)};wa.prototype={Element:L,init:function(a,b,c,d,e){var f=location,g;d=
        this.createElement("svg").attr({version:"1.1"}).css(this.getStyle(d));g=d.element;a.appendChild(g);-1===a.innerHTML.indexOf("xmlns")&&m(g,"xmlns","http://www.w3.org/2000/svg");this.isSVG=!0;this.box=g;this.boxWrapper=d;this.alignedObjects=[];this.url=(Ha||sb)&&E.getElementsByTagName("base").length?f.href.replace(/#.*?$/,"").replace(/([\('\)])/g,"\\$1").replace(/ /g,"%20"):"";this.createElement("desc").add().element.appendChild(E.createTextNode("Created with Highcharts 4.0.4 /Highstock 2.0.4"));this.defs=
        this.createElement("defs").add();this.forExport=e;this.gradients={};this.cache={};this.setSize(b,c,!1);var h;Ha&&a.getBoundingClientRect&&(this.subPixelFix=b=function(){R(a,{left:0,top:0});h=a.getBoundingClientRect();R(a,{left:na(h.left)-h.left+"px",top:na(h.top)-h.top+"px"})},b(),N(J,"resize",b))},getStyle:function(a){return this.style=t({fontFamily:'"Lucida Grande", "Lucida Sans Unicode", Arial, Helvetica, sans-serif',fontSize:"12px"},a)},isHidden:function(){return!this.boxWrapper.getBBox().width},
        destroy:function(){var a=this.defs;this.box=null;this.boxWrapper=this.boxWrapper.destroy();Aa(this.gradients||{});this.gradients=null;a&&(this.defs=a.destroy());this.subPixelFix&&U(J,"resize",this.subPixelFix);return this.alignedObjects=null},createElement:function(a){var b=new this.Element;b.init(this,a);return b},draw:function(){},buildText:function(a){for(var b=a.element,c=this,d=c.forExport,e=l(a.textStr,"").toString(),f=-1!==e.indexOf("<"),g=b.childNodes,h,k,r=m(b,"x"),w=a.styles,D=a.textWidth,
                                                                                                                                                                                                                                                                                                                                                                                     G=w&&w.lineHeight,s=w&&w.HcTextStroke,n=g.length,p=function(a){return G?u(G):c.fontMetrics(/(px|em)$/.test(a&&a.style.fontSize)?a.style.fontSize:w&&w.fontSize||c.style.fontSize||12,a).h};n--;)b.removeChild(g[n]);f||s||-1!==e.indexOf(" ")?(h=/<.*style="([^"]+)".*>/,k=/<.*href="(http[^"]+)".*>/,D&&!a.added&&this.box.appendChild(b),e=f?e.replace(/<(b|strong)>/g,'<span style="font-weight:bold">').replace(/<(i|em)>/g,'<span style="font-style:italic">').replace(/<a/g,"<span").replace(/<\/(b|strong|i|em|a)>/g,
            "</span>").split(/<br.*?>/g):[e],""===e[e.length-1]&&e.pop(),v(e,function(e,f){var g,s=0;e=e.replace(/<span/g,"|||<span").replace(/<\/span>/g,"</span>|||");g=e.split("|||");v(g,function(e){if(""!==e||1===g.length){var G={},l=E.createElementNS("http://www.w3.org/2000/svg","tspan"),n;h.test(e)&&(n=e.match(h)[1].replace(/(;| |^)color([ :])/,"$1fill$2"),m(l,"style",n));k.test(e)&&!d&&(m(l,"onclick",'location.href="'+e.match(k)[1]+'"'),R(l,{cursor:"pointer"}));e=(e.replace(/<(.|\n)*?>/g,"")||" ").replace(/&lt;/g,
            "<").replace(/&gt;/g,">");if(" "!==e){l.appendChild(E.createTextNode(e));s?G.dx=0:f&&null!==r&&(G.x=r);m(l,G);b.appendChild(l);!s&&f&&(!S&&d&&R(l,{display:"block"}),m(l,"dy",p(l)));if(D){e=e.replace(/([^\^])-/g,"$1- ").split(" ");for(var G=1<g.length||1<e.length&&"nowrap"!==w.whiteSpace,Xa,q,v=w.HcHeight,t=[],pb=p(l),qb=1;G&&(e.length||t.length);)delete a.bBox,Xa=a.getBBox(),q=Xa.width,!S&&c.forExport&&(q=c.measureSpanWidth(l.firstChild.data,a.styles)),(Xa=q>D)&&1!==e.length?(l.removeChild(l.firstChild),
            t.unshift(e.pop())):(e=t,t=[],e.length&&(qb++,v&&qb*pb>v?(e=["..."],a.attr("title",a.textStr)):(l=E.createElementNS("http://www.w3.org/2000/svg","tspan"),m(l,{dy:pb,x:r}),n&&m(l,"style",n),b.appendChild(l))),q>D&&(D=q)),e.length&&l.appendChild(E.createTextNode(e.join(" ").replace(/- /g,"-")))}s++}}})})):b.appendChild(E.createTextNode(e))},button:function(a,b,c,d,e,f,g,h,k){var r=this.label(a,b,c,k,null,null,null,null,"button"),w=0,D,l,s,n,m,p;a={x1:0,y1:0,x2:0,y2:1};e=y({"stroke-width":1,stroke:"#CCCCCC",
            fill:{linearGradient:a,stops:[[0,"#FEFEFE"],[1,"#F6F6F6"]]},r:2,padding:5,style:{color:"black"}},e);s=e.style;delete e.style;f=y(e,{stroke:"#68A",fill:{linearGradient:a,stops:[[0,"#FFF"],[1,"#ACF"]]}},f);n=f.style;delete f.style;g=y(e,{stroke:"#68A",fill:{linearGradient:a,stops:[[0,"#9BD"],[1,"#CDF"]]}},g);m=g.style;delete g.style;h=y(e,{style:{color:"#CCC"}},h);p=h.style;delete h.style;N(r.element,ia?"mouseover":"mouseenter",function(){3!==w&&r.attr(f).css(n)});N(r.element,ia?"mouseout":"mouseleave",
            function(){3!==w&&(D=[e,f,g][w],l=[s,n,m][w],r.attr(D).css(l))});r.setState=function(a){(r.state=w=a)?2===a?r.attr(g).css(m):3===a&&r.attr(h).css(p):r.attr(e).css(s)};return r.on("click",function(){3!==w&&d.call(r)}).attr(e).css(t({cursor:"default"},s))},crispLine:function(a,b){a[1]===a[4]&&(a[1]=a[4]=B(a[1])-b%2/2);a[2]===a[5]&&(a[2]=a[5]=B(a[2])+b%2/2);return a},path:function(a){var b={fill:"none"};ba(a)?b.d=a:C(a)&&t(b,a);return this.createElement("path").attr(b)},circle:function(a,b,c){a=C(a)?
            a:{x:a,y:b,r:c};b=this.createElement("circle");b.xSetter=function(a){this.element.setAttribute("cx",a)};b.ySetter=function(a){this.element.setAttribute("cy",a)};return b.attr(a)},arc:function(a,b,c,d,e,f){C(a)&&(b=a.y,c=a.r,d=a.innerR,e=a.start,f=a.end,a=a.x);a=this.symbol("arc",a||0,b||0,c||0,c||0,{innerR:d||0,start:e||0,end:f||0});a.r=c;return a},rect:function(a,b,c,d,e,f){e=C(a)?a.r:e;var g=this.createElement("rect");a=C(a)?a:a===A?{}:{x:a,y:b,width:x(c,0),height:x(d,0)};f!==A&&(a.strokeWidth=
            f,a=g.crisp(a));e&&(a.r=e);g.rSetter=function(a){m(this.element,{rx:a,ry:a})};return g.attr(a)},setSize:function(a,b,c){var d=this.alignedObjects,e=d.length;this.width=a;this.height=b;for(this.boxWrapper[l(c,!0)?"animate":"attr"]({width:a,height:b});e--;)d[e].align()},g:function(a){var b=this.createElement("g");return n(a)?b.attr({"class":"highcharts-"+a}):b},image:function(a,b,c,d,e){var f={preserveAspectRatio:"none"};1<arguments.length&&t(f,{x:b,y:c,width:d,height:e});f=this.createElement("image").attr(f);
            f.element.setAttributeNS?f.element.setAttributeNS("http://www.w3.org/1999/xlink","href",a):f.element.setAttribute("hc-svg-href",a);return f},symbol:function(a,b,c,d,e,f){var g,h=this.symbols[a],h=h&&h(B(b),B(c),d,e,f),k=/^url\((.*?)\)$/,r,w;h?(g=this.path(h),t(g,{symbolName:a,x:b,y:c,width:d,height:e}),f&&t(g,f)):k.test(a)&&(w=function(a,b){a.element&&(a.attr({width:b[0],height:b[1]}),a.alignByTranslate||a.translate(B((d-b[0])/2),B((e-b[1])/2)))},r=a.match(k)[1],a=lb[r]||f&&f.width&&f.height&&[f.width,
            f.height],g=this.image(r).attr({x:b,y:c}),g.isImg=!0,a?w(g,a):(g.attr({width:0,height:0}),qa("img",{onload:function(){w(g,lb[r]=[this.width,this.height])},src:r})));return g},symbols:{circle:function(a,b,c,d){var e=.166*c;return["M",a+c/2,b,"C",a+c+e,b,a+c+e,b+d,a+c/2,b+d,"C",a-e,b+d,a-e,b,a+c/2,b,"Z"]},square:function(a,b,c,d){return["M",a,b,"L",a+c,b,a+c,b+d,a,b+d,"Z"]},triangle:function(a,b,c,d){return["M",a+c/2,b,"L",a+c,b+d,a,b+d,"Z"]},"triangle-down":function(a,b,c,d){return["M",a,b,"L",a+c,
            b,a+c/2,b+d,"Z"]},diamond:function(a,b,c,d){return["M",a+c/2,b,"L",a+c,b+d/2,a+c/2,b+d,a,b+d/2,"Z"]},arc:function(a,b,c,d,e){var f=e.start;c=e.r||c||d;var g=e.end-.001;d=e.innerR;var h=e.open,k=ta(f),r=Ga(f),w=ta(g),g=Ga(g);e=e.end-f<ib?0:1;return["M",a+c*k,b+c*r,"A",c,c,0,e,1,a+c*w,b+c*g,h?"M":"L",a+d*w,b+d*g,"A",d,d,0,e,0,a+d*k,b+d*r,h?"":"Z"]},callout:function(a,b,c,d,e){var f=V(e&&e.r||0,c,d),g=f+6,h=e&&e.anchorX,k=e&&e.anchorY;e=B(e.strokeWidth||0)%2/2;a+=e;b+=e;e=["M",a+f,b,"L",a+c-f,b,"C",
                a+c,b,a+c,b,a+c,b+f,"L",a+c,b+d-f,"C",a+c,b+d,a+c,b+d,a+c-f,b+d,"L",a+f,b+d,"C",a,b+d,a,b+d,a,b+d-f,"L",a,b+f,"C",a,b,a,b,a+f,b];h&&h>c&&k>b+g&&k<b+d-g?e.splice(13,3,"L",a+c,k-6,a+c+6,k,a+c,k+6,a+c,b+d-f):h&&0>h&&k>b+g&&k<b+d-g?e.splice(33,3,"L",a,k+6,a-6,k,a,k-6,a,b+f):k&&k>d&&h>a+g&&h<a+c-g?e.splice(23,3,"L",h+6,b+d,h,b+d+6,h-6,b+d,a+f,b+d):k&&0>k&&h>a+g&&h<a+c-g&&e.splice(3,3,"L",h-6,b,h,b-6,h+6,b,c-f,b);return e}},clipRect:function(a,b,c,d){var e="highcharts-"+Ra++,f=this.createElement("clipPath").attr({id:e}).add(this.defs);
            a=this.rect(a,b,c,d,0).add(f);a.id=e;a.clipPath=f;return a},text:function(a,b,c,d){var e=$||!S&&this.forExport,f={};if(d&&!this.forExport)return this.html(a,b,c);f.x=Math.round(b||0);c&&(f.y=Math.round(c));if(a||0===a)f.text=a;a=this.createElement("text").attr(f);e&&a.css({position:"absolute"});d||(a.xSetter=function(a,b,c){var d=c.getElementsByTagName("tspan"),e,f=c.getAttribute(b),l;for(l=0;l<d.length;l++)e=d[l],e.getAttribute(b)===f&&e.setAttribute(b,a);c.setAttribute(b,a)});return a},fontMetrics:function(a,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              b){a=a||this.style.fontSize;b&&J.getComputedStyle&&(b=b.element||b,a=J.getComputedStyle(b,"").fontSize);a=/px/.test(a)?u(a):/em/.test(a)?12*parseFloat(a):12;var c=24>a?a+4:B(1.2*a),d=B(.8*c);return{h:c,b:d,f:a}},label:function(a,b,c,d,e,f,g,h,k){function r(){var a,b;a=m.element.style;q=(void 0===oa||void 0===z||s.styles.textAlign)&&m.textStr&&m.getBBox();s.width=(oa||q.width||0)+2*K+x;s.height=(z||q.height||0)+2*K;da=K+G.fontMetrics(a&&a.fontSize,m).b;H&&(p||(a=B(-u*K),b=h?-da:0,s.box=p=d?G.symbol(d,
            a,b,s.width,s.height,M):G.rect(a,b,s.width,s.height,0,M["stroke-width"]),p.attr("fill","none").add(s)),p.isImg||p.attr(t({width:B(s.width),height:B(s.height)},M)),M=null)}function w(){var a=s.styles,a=a&&a.textAlign,b=x+K*(1-u),c;c=h?0:da;n(oa)&&q&&("center"===a||"right"===a)&&(b+={center:.5,right:1}[a]*(oa-q.width));if(b!==m.x||c!==m.y)m.attr("x",b),c!==A&&m.attr("y",c);m.x=b;m.y=c}function l(a,b){p?p.attr(a,b):M[a]=b}var G=this,s=G.g(k),m=G.text("",0,0,g).attr({zIndex:1}),p,q,u=0,K=3,x=0,oa,z,C,
            Ya,E=0,M={},da,H;s.onAdd=function(){m.add(s);s.attr({text:a||0===a?a:"",x:b,y:c});p&&n(e)&&s.attr({anchorX:e,anchorY:f})};s.widthSetter=function(a){oa=a};s.heightSetter=function(a){z=a};s.paddingSetter=function(a){n(a)&&a!==K&&(K=a,w())};s.paddingLeftSetter=function(a){n(a)&&a!==x&&(x=a,w())};s.alignSetter=function(a){u={left:0,center:.5,right:1}[a]};s.textSetter=function(a){a!==A&&m.textSetter(a);r();w()};s["stroke-widthSetter"]=function(a,b){a&&(H=!0);E=a%2/2;l(b,a)};s.strokeSetter=s.fillSetter=
            s.rSetter=function(a,b){"fill"===b&&a&&(H=!0);l(b,a)};s.anchorXSetter=function(a,b){e=a;l(b,a+E-C)};s.anchorYSetter=function(a,b){f=a;l(b,a-Ya)};s.xSetter=function(a){s.x=a;u&&(a-=u*((oa||q.width)+K));C=B(a);s.attr("translateX",C)};s.ySetter=function(a){Ya=s.y=B(a);s.attr("translateY",Ya)};var F=s.css;return t(s,{css:function(a){if(a){var b={};a=y(a);v(s.textProps,function(c){a[c]!==A&&(b[c]=a[c],delete a[c])});m.css(b)}return F.call(s,a)},getBBox:function(){return{width:q.width+2*K,height:q.height+
            2*K,x:q.x-K,y:q.y-K}},shadow:function(a){p&&p.shadow(a);return s},destroy:function(){U(s.element,"mouseenter");U(s.element,"mouseleave");m&&(m=m.destroy());p&&(p=p.destroy());L.prototype.destroy.call(s);s=G=r=w=l=null}})}};la.prototype={addLabel:function(){var a=this.axis,b=a.options,c=a.chart,d=a.horiz,e=a.categories,f=a.names,g=this.pos,h=b.labels,k=h.rotation,r=a.tickPositions,d=d&&e&&!h.step&&!h.staggerLines&&!h.rotation&&c.plotWidth/r.length||!d&&(c.margin[3]||.33*c.chartWidth),w=g===r[0],D=
        g===r[r.length-1],G,f=e?l(e[g],f[g],g):g,e=this.label,s=r.info;a.isDatetimeAxis&&s&&(G=b.dateTimeLabelFormats[s.higherRanks[g]||s.unitName]);this.isFirst=w;this.isLast=D;b=a.labelFormatter.call({axis:a,chart:c,isFirst:w,isLast:D,dateTimeLabelFormat:G,value:a.isLog?Z(p(f)):f});g=d&&{width:x(1,B(d-2*(h.padding||10)))+"px"};n(e)?e&&e.attr({text:b}).css(g):(G={align:a.labelAlign},P(k)&&(G.rotation=k),d&&h.ellipsis&&(g.HcHeight=a.len/r.length),this.label=e=n(b)&&h.enabled?c.renderer.text(b,0,0,h.useHTML).attr(G).css(t(g,
        h.style)).add(a.labelGroup):null,a.tickBaseline=c.renderer.fontMetrics(h.style.fontSize,e).b,k&&2===a.side&&(a.tickBaseline*=ta(k*jb)));this.yOffset=e?l(h.y,a.tickBaseline+(2===a.side?8:-(e.getBBox().height/2))):0},getLabelSize:function(){var a=this.label,b=this.axis;return a?a.getBBox()[b.horiz?"height":"width"]:0},getLabelSides:function(){var a=this.label.getBBox(),b=this.axis,c=b.horiz,d=b.options.labels,a=c?a.width:a.height,b=c?d.x-a*{left:0,center:.5,right:1}[b.labelAlign]:0;return[b,c?a+b:a]},
        handleOverflow:function(a,b){var c=!0,d=this.axis,e=this.isFirst,f=this.isLast,g=d.horiz?b.x:b.y,h=d.reversed,k=d.tickPositions,r=this.getLabelSides(),w=r[0],r=r[1],l,n,s,m=this.label.line;l=m||0;n=d.labelEdge;s=d.justifyLabels&&(e||f);n[l]===A||g+w>n[l]?n[l]=g+r:s||(c=!1);if(s){l=(n=d.justifyToPlot)?d.pos:0;n=n?l+d.len:d.chart.chartWidth;do a+=e?1:-1,s=d.ticks[k[a]];while(k[a]&&(!s||!s.label||s.label.line!==m));d=s&&s.label.xy&&s.label.xy.x+s.getLabelSides()[e?0:1];e&&!h||f&&h?g+w<l&&(g=l-w,s&&g+
            r>d&&(c=!1)):g+r>n&&(g=n-r,s&&g+w<d&&(c=!1));b.x=g}return c},getPosition:function(a,b,c,d){var e=this.axis,f=e.chart,g=d&&f.oldChartHeight||f.chartHeight;return{x:a?e.translate(b+c,null,null,d)+e.transB:e.left+e.offset+(e.opposite?(d&&f.oldChartWidth||f.chartWidth)-e.right-e.left:0),y:a?g-e.bottom+e.offset-(e.opposite?e.height:0):g-e.translate(b+c,null,null,d)-e.transB}},getLabelPosition:function(a,b,c,d,e,f,g,h){var k=this.axis,r=k.transA,l=k.reversed,D=k.staggerLines;a=a+e.x-(f&&d?f*r*(l?-1:1):
            0);b=b+this.yOffset-(f&&!d?f*r*(l?1:-1):0);D&&(c.line=g/(h||1)%D,b+=k.labelOffset/D*c.line);return{x:a,y:b}},getMarkPath:function(a,b,c,d,e,f){return f.crispLine(["M",a,b,"L",a+(e?0:-c),b+(e?c:0)],d)},render:function(a,b,c){var d=this.axis,e=d.options,f=d.chart.renderer,g=d.horiz,h=this.type,k=this.label,r=this.pos,w=e.labels,D=this.gridLine,n=h?h+"Grid":"grid",s=h?h+"Tick":"tick",m=e[n+"LineWidth"],p=e[n+"LineColor"],q=e[n+"LineDashStyle"],v=e[s+"Length"],n=e[s+"Width"]||0,t=e[s+"Color"],u=e[s+"Position"],
            s=this.mark,x=w.step,y=!0,B=d.tickmarkOffset,z=this.getPosition(g,r,B,b),C=z.x,z=z.y,M=g&&C===d.pos+d.len||!g&&z===d.pos?-1:1;c=l(c,1);this.isActive=!0;if(m&&(r=d.getPlotLinePath(r+B,m*M,b,!0),D===A&&(D={stroke:p,"stroke-width":m},q&&(D.dashstyle=q),h||(D.zIndex=1),b&&(D.opacity=0),this.gridLine=D=m?f.path(r).attr(D).add(d.gridGroup):null),!b&&D&&r))D[this.isNew?"attr":"animate"]({d:r,opacity:c});n&&v&&("inside"===u&&(v=-v),d.opposite&&(v=-v),h=this.getMarkPath(C,z,v,n*M,g,f),s?s.animate({d:h,opacity:c}):
            this.mark=f.path(h).attr({stroke:t,"stroke-width":n,opacity:c}).add(d.axisGroup));k&&!isNaN(C)&&(k.xy=z=this.getLabelPosition(C,z,k,g,w,B,a,x),this.isFirst&&!this.isLast&&!l(e.showFirstLabel,1)||this.isLast&&!this.isFirst&&!l(e.showLastLabel,1)?y=!1:d.isRadial||w.step||w.rotation||b||0===c||(y=this.handleOverflow(a,z)),x&&a%x&&(y=!1),y&&!isNaN(z.y)?(z.opacity=c,k[this.isNew?"attr":"animate"](z),this.isNew=!1):k.attr("y",-9999))},destroy:function(){Aa(this,this.axis)}};ma.prototype={defaultOptions:{dateTimeLabelFormats:{millisecond:"%H:%M:%S.%L",
        second:"%H:%M:%S",minute:"%H:%M",hour:"%H:%M",day:"%e. %b",week:"%e. %b",month:"%b '%y",year:"%Y"},endOnTick:!1,gridLineColor:"#C0C0C0",labels:Va,lineColor:"#C0D0E0",lineWidth:1,minPadding:.01,maxPadding:.01,minorGridLineColor:"#E0E0E0",minorGridLineWidth:1,minorTickColor:"#A0A0A0",minorTickLength:2,minorTickPosition:"outside",startOfWeek:1,startOnTick:!1,tickColor:"#C0D0E0",tickLength:10,tickmarkPlacement:"between",tickPixelInterval:100,tickPosition:"outside",tickWidth:1,title:{align:"middle",style:{color:"#707070"}},
        type:"linear"},defaultYAxisOptions:{endOnTick:!0,gridLineWidth:1,tickPixelInterval:72,showLastLabel:!0,labels:{x:-8,y:3},lineWidth:0,maxPadding:.05,minPadding:.05,startOnTick:!0,tickWidth:0,title:{rotation:270,text:"Values"},stackLabels:{enabled:!1,formatter:function(){return aa(this.total,-1)},style:Va.style}},defaultLeftAxisOptions:{labels:{x:-15,y:null},title:{rotation:270}},defaultRightAxisOptions:{labels:{x:15,y:null},title:{rotation:90}},defaultBottomAxisOptions:{labels:{x:0,y:null},title:{rotation:0}},
        defaultTopAxisOptions:{labels:{x:0,y:-15},title:{rotation:0}},init:function(a,b){var c=b.isX;this.horiz=a.inverted?!c:c;this.coll=(this.isXAxis=c)?"xAxis":"yAxis";this.opposite=b.opposite;this.side=b.side||(this.horiz?this.opposite?0:2:this.opposite?1:3);this.setOptions(b);var d=this.options,e=d.type;this.labelFormatter=d.labels.formatter||this.defaultLabelFormatter;this.userOptions=b;this.minPixelPadding=0;this.chart=a;this.reversed=d.reversed;this.zoomEnabled=!1!==d.zoomEnabled;this.categories=
            d.categories||"category"===e;this.names=[];this.isLog="logarithmic"===e;this.isDatetimeAxis="datetime"===e;this.isLinked=n(d.linkedTo);this.tickmarkOffset=this.categories&&"between"===d.tickmarkPlacement&&1===l(d.tickInterval,1)?.5:0;this.ticks={};this.labelEdge=[];this.minorTicks={};this.plotLinesAndBands=[];this.alternateBands={};this.len=0;this.minRange=this.userMinRange=d.minRange||d.maxZoom;this.range=d.range;this.offset=d.offset||0;this.stacks={};this.oldStacks={};this.min=this.max=null;this.crosshair=
            l(d.crosshair,pa(a.options.tooltip.crosshairs)[c?0:1],!1);var f,d=this.options.events;-1===vb(this,a.axes)&&(c&&!this.isColorAxis?a.axes.splice(a.xAxis.length,0,this):a.axes.push(this),a[this.coll].push(this));this.series=this.series||[];a.inverted&&c&&this.reversed===A&&(this.reversed=!0);this.removePlotLine=this.removePlotBand=this.removePlotBandOrLine;for(f in d)N(this,f,d[f]);this.isLog&&(this.val2lin=fa,this.lin2val=p)},setOptions:function(a){this.options=y(this.defaultOptions,this.isXAxis?{}:
            this.defaultYAxisOptions,[this.defaultTopAxisOptions,this.defaultRightAxisOptions,this.defaultBottomAxisOptions,this.defaultLeftAxisOptions][this.side],y(F[this.coll],a))},defaultLabelFormatter:function(){var a=this.axis,b=this.value,c=a.categories,d=this.dateTimeLabelFormat,e=F.lang.numericSymbols,f=e&&e.length,g,h=a.options.labels.format,a=a.isLog?b:a.tickInterval;if(h)g=xa(h,this);else if(c)g=b;else if(d)g=ya(d,b);else if(f&&1E3<=a)for(;f--&&g===A;)c=Math.pow(1E3,f+1),a>=c&&null!==e[f]&&(g=aa(b/
            c,-1)+e[f]);g===A&&(g=1E4<=Y(b)?aa(b,0):aa(b,-1,A,""));return g},getSeriesExtremes:function(){var a=this,b=a.chart;a.hasVisibleSeries=!1;a.dataMin=a.dataMax=a.ignoreMinPadding=a.ignoreMaxPadding=null;a.buildStacks&&a.buildStacks();v(a.series,function(c){if(c.visible||!b.options.chart.ignoreHiddenSeries){var d;d=c.options.threshold;var e;a.hasVisibleSeries=!0;a.isLog&&0>=d&&(d=null);a.isXAxis?(d=c.xData,d.length&&(a.dataMin=V(l(a.dataMin,d[0]),za(d)),a.dataMax=x(l(a.dataMax,d[0]),ra(d)))):(c.getExtremes(),
            e=c.dataMax,c=c.dataMin,n(c)&&n(e)&&(a.dataMin=V(l(a.dataMin,c),c),a.dataMax=x(l(a.dataMax,e),e)),n(d)&&(a.dataMin>=d?(a.dataMin=d,a.ignoreMinPadding=!0):a.dataMax<d&&(a.dataMax=d,a.ignoreMaxPadding=!0)))}})},translate:function(a,b,c,d,e,f){var g=1,h=0,k=d?this.oldTransA:this.transA;d=d?this.oldMin:this.min;var r=this.minPixelPadding;e=(this.options.ordinal||this.isLog&&e)&&this.lin2val;k||(k=this.transA);c&&(g*=-1,h=this.len);this.reversed&&(g*=-1,h-=g*(this.sector||this.len));b?(a=a*g+h-r,a=a/k+
            d,e&&(a=this.lin2val(a))):(e&&(a=this.val2lin(a)),"between"===f&&(f=.5),a=g*(a-d)*k+h+g*r+(P(f)?k*f*this.pointRange:0));return a},toPixels:function(a,b){return this.translate(a,!1,!this.horiz,null,!0)+(b?0:this.pos)},toValue:function(a,b){return this.translate(a-(b?0:this.pos),!0,!this.horiz,null,!0)},getPlotLinePath:function(a,b,c,d,e){var f=this.chart,g=this.left,h=this.top,k,r,w=c&&f.oldChartHeight||f.chartHeight,n=c&&f.oldChartWidth||f.chartWidth,m;k=this.transB;e=l(e,this.translate(a,null,null,
            c));a=c=B(e+k);k=r=B(w-e-k);if(isNaN(e))m=!0;else if(this.horiz){if(k=h,r=w-this.bottom,a<g||a>g+this.width)m=!0}else if(a=g,c=n-this.right,k<h||k>h+this.height)m=!0;return m&&!d?null:f.renderer.crispLine(["M",a,k,"L",c,r],b||1)},getLinearTickPositions:function(a,b,c){var d,e=Z(I(b/a)*a),f=Z(na(c/a)*a),g=[];if(b===c&&P(b))return[b];for(b=e;b<=f;){g.push(b);b=Z(b+a);if(b===d)break;d=b}return g},getMinorTickPositions:function(){var a=this.options,b=this.tickPositions,c=this.minorTickInterval,d=[],e;
            if(this.isLog)for(e=b.length,a=1;a<e;a++)d=d.concat(this.getLogTickPositions(c,b[a-1],b[a],!0));else if(this.isDatetimeAxis&&"auto"===a.minorTickInterval)d=d.concat(this.getTimeTicks(this.normalizeTimeTickInterval(c),this.min,this.max,a.startOfWeek)),d[0]<this.min&&d.shift();else for(b=this.min+(b[0]-this.min)%c;b<=this.max;b+=c)d.push(b);return d},adjustForMinRange:function(){var a=this.options,b=this.min,c=this.max,d,e=this.dataMax-this.dataMin>=this.minRange,f,g,h,k,r;this.isXAxis&&this.minRange===
            A&&!this.isLog&&(n(a.min)||n(a.max)?this.minRange=null:(v(this.series,function(a){k=a.xData;for(g=r=a.xIncrement?1:k.length-1;0<g;g--)if(h=k[g]-k[g-1],f===A||h<f)f=h}),this.minRange=V(5*f,this.dataMax-this.dataMin)));if(c-b<this.minRange){var w=this.minRange;d=(w-c+b)/2;d=[b-d,l(a.min,b-d)];e&&(d[2]=this.dataMin);b=ra(d);c=[b+w,l(a.max,b+w)];e&&(c[2]=this.dataMax);c=za(c);c-b<w&&(d[0]=c-w,d[1]=l(a.min,c-w),b=ra(d))}this.min=b;this.max=c},setAxisTranslation:function(a){var b=this,c=b.max-b.min,d=b.axisPointRange||
            0,e,f=0,g=0,h=b.linkedParent,k=!!b.categories,r=b.transA;if(b.isXAxis||k||d)h?(f=h.minPointOffset,g=h.pointRangePadding):v(b.series,function(a){var h=k?1:b.isXAxis?a.pointRange:b.axisPointRange||0,r=a.options.pointPlacement,l=a.closestPointRange;h>c&&(h=0);d=x(d,h);f=x(f,X(r)?0:h/2);g=x(g,"on"===r?0:h);!a.noSharedTooltip&&n(l)&&(e=n(e)?V(e,l):l)}),h=b.ordinalSlope&&e?b.ordinalSlope/e:1,b.minPointOffset=f*=h,b.pointRangePadding=g*=h,b.pointRange=V(d,c),b.closestPointRange=e;a&&(b.oldTransA=r);b.translationSlope=
            b.transA=r=b.len/(c+g||1);b.transB=b.horiz?b.left:b.bottom;b.minPixelPadding=r*f},setTickPositions:function(a){var b=this,c=b.chart,d=b.options,e=d.startOnTick,f=d.endOnTick,g=b.isLog,h=b.isDatetimeAxis,k=b.isXAxis,r=b.isLinked,w=b.options.tickPositioner,m=d.maxPadding,p=d.minPadding,s=d.tickInterval,q=d.minTickInterval,t=d.tickPixelInterval,u,A=b.categories;r?(b.linkedParent=c[b.coll][d.linkedTo],c=b.linkedParent.getExtremes(),b.min=l(c.min,c.dataMin),b.max=l(c.max,c.dataMax),d.type!==b.linkedParent.options.type&&
            Q(11,1)):(b.min=l(b.userMin,d.min,b.dataMin),b.max=l(b.userMax,d.max,b.dataMax));g&&(!a&&0>=V(b.min,l(b.dataMin,b.min))&&Q(10,1),b.min=Z(fa(b.min)),b.max=Z(fa(b.max)));b.range&&n(b.max)&&(b.userMin=b.min=x(b.min,b.max-b.range),b.userMax=b.max,b.range=null);b.beforePadding&&b.beforePadding();b.adjustForMinRange();!(A||b.axisPointRange||b.usePercentage||r)&&n(b.min)&&n(b.max)&&(c=b.max-b.min)&&(n(d.min)||n(b.userMin)||!p||!(0>b.dataMin)&&b.ignoreMinPadding||(b.min-=c*p),n(d.max)||n(b.userMax)||!m||
            !(0<b.dataMax)&&b.ignoreMaxPadding||(b.max+=c*m));P(d.floor)&&(b.min=x(b.min,d.floor));P(d.ceiling)&&(b.max=V(b.max,d.ceiling));b.min===b.max||void 0===b.min||void 0===b.max?b.tickInterval=1:r&&!s&&t===b.linkedParent.options.tickPixelInterval?b.tickInterval=b.linkedParent.tickInterval:(b.tickInterval=l(s,A?1:(b.max-b.min)*t/x(b.len,t)),!n(s)&&b.len<t&&!this.isRadial&&!this.isLog&&!A&&e&&f&&(u=!0,b.tickInterval/=4));k&&!a&&v(b.series,function(a){a.processData(b.min!==b.oldMin||b.max!==b.oldMax)});
            b.setAxisTranslation(!0);b.beforeSetTickPositions&&b.beforeSetTickPositions();b.postProcessTickInterval&&(b.tickInterval=b.postProcessTickInterval(b.tickInterval));b.pointRange&&(b.tickInterval=x(b.pointRange,b.tickInterval));!s&&b.tickInterval<q&&(b.tickInterval=q);h||g||s||(b.tickInterval=cb(b.tickInterval,null,H.pow(10,I(H.log(b.tickInterval)/H.LN10)),l(d.allowDecimals,!(1<b.tickInterval&&5>b.tickInterval&&1E3<b.max&&9999>b.max))));b.minorTickInterval="auto"===d.minorTickInterval&&b.tickInterval?
                b.tickInterval/5:d.minorTickInterval;b.tickPositions=a=d.tickPositions?[].concat(d.tickPositions):w&&w.apply(b,[b.min,b.max]);a||(!b.ordinalPositions&&(b.max-b.min)/b.tickInterval>x(2*b.len,200)&&Q(19,!0),a=h?b.getTimeTicks(b.normalizeTimeTickInterval(b.tickInterval,d.units),b.min,b.max,d.startOfWeek,b.ordinalPositions,b.closestPointRange,!0):g?b.getLogTickPositions(b.tickInterval,b.min,b.max):b.getLinearTickPositions(b.tickInterval,b.min,b.max),u&&a.splice(1,a.length-2),b.tickPositions=a);r||(d=
                a[0],g=a[a.length-1],h=b.minPointOffset||0,e?b.min=d:b.min-h>d&&a.shift(),f?b.max=g:b.max+h<g&&a.pop(),0===a.length&&n(d)&&a.push((g+d)/2),1===a.length&&(e=1E13<Y(b.max)?1:.001,b.min-=e,b.max+=e))},setMaxTicks:function(){var a=this.chart,b=a.maxTicks||{},c=this.tickPositions,d=this._maxTicksKey=[this.coll,this.pos,this.len].join("-");!this.isLinked&&!this.isDatetimeAxis&&c&&c.length>(b[d]||0)&&!1!==this.options.alignTicks&&(b[d]=c.length);a.maxTicks=b},adjustTickAmount:function(){var a=this._maxTicksKey,
            b=this.tickPositions,c=this.chart.maxTicks;if(c&&c[a]&&!this.isDatetimeAxis&&!this.categories&&!this.isLinked&&!1!==this.options.alignTicks&&this.min!==A){var d=this.tickAmount,e=b.length;this.tickAmount=a=c[a];if(e<a){for(;b.length<a;)b.push(Z(b[b.length-1]+this.tickInterval));this.transA*=(e-1)/(a-1);this.max=b[b.length-1]}n(d)&&a!==d&&(this.isDirty=!0)}},setScale:function(){var a=this.stacks,b,c,d,e;this.oldMin=this.min;this.oldMax=this.max;this.oldAxisLength=this.len;this.setAxisSize();e=this.len!==
            this.oldAxisLength;v(this.series,function(a){if(a.isDirtyData||a.isDirty||a.xAxis.isDirty)d=!0});if(e||d||this.isLinked||this.forceRedraw||this.userMin!==this.oldUserMin||this.userMax!==this.oldUserMax){if(!this.isXAxis)for(b in a)for(c in a[b])a[b][c].total=null,a[b][c].cum=0;this.forceRedraw=!1;this.getSeriesExtremes();this.setTickPositions();this.oldUserMin=this.userMin;this.oldUserMax=this.userMax;this.isDirty||(this.isDirty=e||this.min!==this.oldMin||this.max!==this.oldMax)}else if(!this.isXAxis)for(b in this.oldStacks&&
            (a=this.stacks=this.oldStacks),a)for(c in a[b])a[b][c].cum=a[b][c].total;this.setMaxTicks()},setExtremes:function(a,b,c,d,e){var f=this,g=f.chart;c=l(c,!0);e=t(e,{min:a,max:b});O(f,"setExtremes",e,function(){f.userMin=a;f.userMax=b;f.eventArgs=e;f.isDirtyExtremes=!0;c&&g.redraw(d)})},zoom:function(a,b){var c=this.dataMin,d=this.dataMax,e=this.options;this.allowZoomOutside||(n(c)&&a<=V(c,l(e.min,c))&&(a=A),n(d)&&b>=x(d,l(e.max,d))&&(b=A));this.displayBtn=a!==A||b!==A;this.setExtremes(a,b,!1,A,{trigger:"zoom"});
            return!0},setAxisSize:function(){var a=this.chart,b=this.options,c=b.offsetLeft||0,d=this.horiz,e=l(b.width,a.plotWidth-c+(b.offsetRight||0)),f=l(b.height,a.plotHeight),g=l(b.top,a.plotTop),b=l(b.left,a.plotLeft+c),c=/%$/;c.test(f)&&(f=parseInt(f,10)/100*a.plotHeight);c.test(g)&&(g=parseInt(g,10)/100*a.plotHeight+a.plotTop);this.left=b;this.top=g;this.width=e;this.height=f;this.bottom=a.chartHeight-f-g;this.right=a.chartWidth-e-b;this.len=x(d?e:f,0);this.pos=d?b:g},getExtremes:function(){var a=this.isLog;
            return{min:a?Z(p(this.min)):this.min,max:a?Z(p(this.max)):this.max,dataMin:this.dataMin,dataMax:this.dataMax,userMin:this.userMin,userMax:this.userMax}},getThreshold:function(a){var b=this.isLog,c=b?p(this.min):this.min,b=b?p(this.max):this.max;c>a||null===a?a=c:b<a&&(a=b);return this.translate(a,0,1,0,1)},autoLabelAlign:function(a){a=(l(a,0)-90*this.side+720)%360;return 15<a&&165>a?"right":195<a&&345>a?"left":"center"},getOffset:function(){var a=this,b=a.chart,c=b.renderer,d=a.options,e=a.tickPositions,
            f=a.ticks,g=a.horiz,h=a.side,k=b.inverted?[1,0,3,2][h]:h,r,w,m=0,p,s=0,q=d.title,t=d.labels,u=0,z=b.axisOffset,b=b.clipOffset,K=[-1,1,1,-1][h],y,B=1,C=l(t.maxStaggerLines,5),E,H,F,M,da;a.hasData=r=a.hasVisibleSeries||n(a.min)&&n(a.max)&&!!e;a.showAxis=w=r||l(d.showEmpty,!0);a.staggerLines=a.horiz&&t.staggerLines;a.axisGroup||(a.gridGroup=c.g("grid").attr({zIndex:d.gridZIndex||1}).add(),a.axisGroup=c.g("axis").attr({zIndex:d.zIndex||2}).add(),a.labelGroup=c.g("axis-labels").attr({zIndex:t.zIndex||
            7}).addClass("highcharts-"+a.coll.toLowerCase()+"-labels").add());if(r||a.isLinked){a.labelAlign=l(t.align||a.autoLabelAlign(t.rotation));v(e,function(b){f[b]?f[b].addLabel():f[b]=new la(a,b)});if(a.horiz&&!a.staggerLines&&C&&!t.rotation){for(r=a.reversed?[].concat(e).reverse():e;B<C;){E=[];H=!1;for(y=0;y<r.length;y++)F=r[y],M=(M=f[F].label&&f[F].label.getBBox())?M.width:0,da=y%B,M&&(F=a.translate(F),E[da]!==A&&F<E[da]&&(H=!0),E[da]=F+M);if(H)B++;else break}1<B&&(a.staggerLines=B)}v(e,function(b){if(0===
            h||2===h||{1:"left",3:"right"}[h]===a.labelAlign)u=x(f[b].getLabelSize(),u)});a.staggerLines&&(u*=a.staggerLines,a.labelOffset=u)}else for(y in f)f[y].destroy(),delete f[y];q&&q.text&&!1!==q.enabled&&(a.axisTitle||(a.axisTitle=c.text(q.text,0,0,q.useHTML).attr({zIndex:7,rotation:q.rotation||0,align:q.textAlign||{low:"left",middle:"center",high:"right"}[q.align]}).addClass("highcharts-"+this.coll.toLowerCase()+"-title").css(q.style).add(a.axisGroup),a.axisTitle.isNew=!0),w&&(m=a.axisTitle.getBBox()[g?
            "height":"width"],p=q.offset,s=n(p)?0:l(q.margin,g?5:10)),a.axisTitle[w?"show":"hide"]());a.offset=K*l(d.offset,z[h]);c=2===h?a.tickBaseline:0;g=u+s+(u&&K*(g?l(t.y,a.tickBaseline+8):t.x)-c);a.axisTitleMargin=l(p,g);z[h]=x(z[h],a.axisTitleMargin+m+K*a.offset,g);b[k]=x(b[k],2*I(d.lineWidth/2))},getLinePath:function(a){var b=this.chart,c=this.opposite,d=this.offset,e=this.horiz,f=this.left+(c?this.width:0)+d,d=b.chartHeight-this.bottom-(c?this.height:0)+d;c&&(a*=-1);return b.renderer.crispLine(["M",
            e?this.left:f,e?d:this.top,"L",e?b.chartWidth-this.right:f,e?d:b.chartHeight-this.bottom],a)},getTitlePosition:function(){var a=this.horiz,b=this.left,c=this.top,d=this.len,e=this.options.title,f=a?b:c,g=this.opposite,h=this.offset,k=u(e.style.fontSize||12),d={low:f+(a?0:d),middle:f+d/2,high:f+(a?d:0)}[e.align],b=(a?c+this.height:b)+(a?1:-1)*(g?-1:1)*this.axisTitleMargin+(2===this.side?k:0);return{x:a?d:b+(g?this.width:0)+h+(e.x||0),y:a?b-(g?this.height:0)+h:d+(e.y||0)}},render:function(){var a=this,
            b=a.horiz,c=a.reversed,d=a.chart,e=d.renderer,f=a.options,g=a.isLog,h=a.isLinked,k=a.tickPositions,r,l=a.axisTitle,m=a.ticks,q=a.minorTicks,s=a.alternateBands,t=f.stackLabels,u=f.alternateGridColor,x=a.tickmarkOffset,y=f.lineWidth,z=d.hasRendered&&n(a.oldMin)&&!isNaN(a.oldMin),B=a.hasData,C=a.showAxis,E,F=f.labels.overflow,H=a.justifyLabels=b&&!1!==F,I;a.labelEdge.length=0;a.justifyToPlot="justify"===F;v([m,q,s],function(a){for(var b in a)a[b].isActive=!1});if(B||h)a.minorTickInterval&&!a.categories&&
        v(a.getMinorTickPositions(),function(b){q[b]||(q[b]=new la(a,b,"minor"));z&&q[b].isNew&&q[b].render(null,!0);q[b].render(null,!1,1)}),k.length&&(r=k.slice(),(b&&c||!b&&!c)&&r.reverse(),H&&(r=r.slice(1).concat([r[0]])),v(r,function(b,c){H&&(c=c===r.length-1?0:c+1);if(!h||b>=a.min&&b<=a.max)m[b]||(m[b]=new la(a,b)),z&&m[b].isNew&&m[b].render(c,!0,.1),m[b].render(c)}),x&&0===a.min&&(m[-1]||(m[-1]=new la(a,-1,null,!0)),m[-1].render(-1))),u&&v(k,function(b,c){0===c%2&&b<a.max&&(s[b]||(s[b]=new ca.PlotLineOrBand(a)),
            E=b+x,I=k[c+1]!==A?k[c+1]+x:a.max,s[b].options={from:g?p(E):E,to:g?p(I):I,color:u},s[b].render(),s[b].isActive=!0)}),a._addedPlotLB||(v((f.plotLines||[]).concat(f.plotBands||[]),function(b){a.addPlotBandOrLine(b)}),a._addedPlotLB=!0);v([m,q,s],function(a){var b,c,e=[],f=T?T.duration||500:0,g=function(){for(c=e.length;c--;)a[e[c]]&&!a[e[c]].isActive&&(a[e[c]].destroy(),delete a[e[c]])};for(b in a)a[b].isActive||(a[b].render(b,!1,0),a[b].isActive=!1,e.push(b));a!==s&&d.hasRendered&&f?f&&setTimeout(g,
            f):g()});y&&(b=a.getLinePath(y),a.axisLine?a.axisLine.animate({d:b}):a.axisLine=e.path(b).attr({stroke:f.lineColor,"stroke-width":y,zIndex:7}).add(a.axisGroup),a.axisLine[C?"show":"hide"]());l&&C&&(l[l.isNew?"attr":"animate"](a.getTitlePosition()),l.isNew=!1);t&&t.enabled&&a.renderStackTotals();a.isDirty=!1},redraw:function(){this.render();v(this.plotLinesAndBands,function(a){a.render()});v(this.series,function(a){a.isDirty=!0})},destroy:function(a){var b=this,c=b.stacks,d,e=b.plotLinesAndBands;a||
        U(b);for(d in c)Aa(c[d]),c[d]=null;v([b.ticks,b.minorTicks,b.alternateBands],function(a){Aa(a)});for(a=e.length;a--;)e[a].destroy();v("stackTotalGroup axisLine axisTitle axisGroup cross gridGroup labelGroup".split(" "),function(a){b[a]&&(b[a]=b[a].destroy())});this.cross&&this.cross.destroy()},drawCrosshair:function(a,b){if(this.crosshair)if(!1===(n(b)||!l(this.crosshair.snap,!0)))this.hideCrosshair();else{var c,d=this.crosshair,e=d.animation;l(d.snap,!0)?n(b)&&(c=this.chart.inverted!=this.horiz?
            b.plotX:this.len-b.plotY):c=this.horiz?a.chartX-this.pos:this.len-a.chartY+this.pos;c=this.isRadial?this.getPlotLinePath(this.isXAxis?b.x:l(b.stackY,b.y)):this.getPlotLinePath(null,null,null,null,c);if(null===c)this.hideCrosshair();else if(this.cross)this.cross.attr({visibility:"visible"})[e?"animate":"attr"]({d:c},e);else e={"stroke-width":d.width||1,stroke:d.color||"#C0C0C0",zIndex:d.zIndex||2},d.dashStyle&&(e.dashstyle=d.dashStyle),this.cross=this.chart.renderer.path(c).attr(e).add()}},hideCrosshair:function(){this.cross&&
        this.cross.hide()}};t(ma.prototype,void 0);ma.prototype.getTimeTicks=function(a,b,c,d){var e=[],f={},g=F.global.useUTC,h,k=new ja(b-ka),r=a.unitRange,w=a.count;if(n(b)){r>=z.second&&(k.setMilliseconds(0),k.setSeconds(r>=z.minute?0:w*I(k.getSeconds()/w)));if(r>=z.minute)k[eb](r>=z.hour?0:w*I(k[Ma]()/w));if(r>=z.hour)k[fb](r>=z.day?0:w*I(k[Na]()/w));if(r>=z.day)k[Pa](r>=z.month?1:w*I(k[sa]()/w));r>=z.month&&(k[gb](r>=z.year?0:w*I(k[Ea]()/w)),h=k[Fa]());if(r>=z.year)k[hb](h-h%w);if(r===z.week)k[Pa](k[sa]()-
        k[Oa]()+l(d,1));b=1;ka&&(k=new ja(k.getTime()+ka));h=k[Fa]();d=k.getTime();for(var m=k[Ea](),p=k[sa](),s=(z.day+(g?ka:6E4*k.getTimezoneOffset()))%z.day;d<c;)e.push(d),d=r===z.year?Da(h+b*w,0):r===z.month?Da(h,m+b*w):g||r!==z.day&&r!==z.week?d+r*w:Da(h,m,p+b*w*(r===z.day?1:7)),b++;e.push(d);v(Ta(e,function(a){return r<=z.hour&&a%z.day===s}),function(a){f[a]="day"})}e.info=t(a,{higherRanks:f,totalRange:r*w});return e};ma.prototype.normalizeTimeTickInterval=function(a,b){var c=b||[["millisecond",[1,
        2,5,10,20,25,50,100,200,500]],["second",[1,2,5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",[1,2,3,4,6,8,12]],["day",[1,2]],["week",[1,2]],["month",[1,2,3,4,6]],["year",null]],d=c[c.length-1],e=z[d[0]],f=d[1],g;for(g=0;g<c.length&&!(d=c[g],e=z[d[0]],f=d[1],c[g+1]&&a<=(e*f[f.length-1]+z[c[g+1][0]])/2);g++);e===z.year&&a<5*e&&(f=[1,2,5]);c=cb(a/e,f,"year"===d[0]?x(H.pow(10,I(H.log(a/e)/H.LN10)),1):1);return{unitRange:e,count:c,unitName:d[0]}};var Za=ca.Legend=function(a,b){this.init(a,b)};Za.prototype=
    {init:function(a,b){var c=this,d=b.itemStyle,e=l(b.padding,8),f=b.itemMarginTop||0;this.options=b;b.enabled&&(c.itemStyle=d,c.itemHiddenStyle=y(d,b.itemHiddenStyle),c.itemMarginTop=f,c.padding=e,c.initialItemX=e,c.initialItemY=e-5,c.maxItemWidth=0,c.chart=a,c.itemHeight=0,c.lastLineHeight=0,c.symbolWidth=l(b.symbolWidth,16),c.pages=[],c.render(),N(c.chart,"endResize",function(){c.positionCheckboxes()}))},colorizeItem:function(a,b){var c=this.options,d=a.legendItem,e=a.legendLine,f=a.legendSymbol,
        g=this.itemHiddenStyle.color,c=b?c.itemStyle.color:g,h=b?a.legendColor||a.color||"#CCC":g,g=a.options&&a.options.marker,k={fill:h},r;d&&d.css({fill:c,color:c});e&&e.attr({stroke:h});if(f){if(g&&f.isMarker)for(r in k.stroke=h,g=a.convertAttribs(g),g)d=g[r],d!==A&&(k[r]=d);f.attr(k)}},positionItem:function(a){var b=this.options,c=b.symbolPadding,b=!b.rtl,d=a._legendItemPos,e=d[0],d=d[1],f=a.checkbox;a.legendGroup&&a.legendGroup.translate(b?e:this.legendWidth-e-2*c-4,d);f&&(f.x=e,f.y=d)},destroyItem:function(a){var b=
        a.checkbox;v(["legendItem","legendLine","legendSymbol","legendGroup"],function(b){a[b]&&(a[b]=a[b].destroy())});b&&Ba(a.checkbox)},destroy:function(){var a=this.group,b=this.box;b&&(this.box=b.destroy());a&&(this.group=a.destroy())},positionCheckboxes:function(a){var b=this.group.alignAttr,c,d=this.clipHeight||this.legendHeight;b&&(c=b.translateY,v(this.allItems,function(e){var f=e.checkbox,g;f&&(g=c+f.y+(a||0)+3,R(f,{left:b.translateX+e.checkboxOffset+f.x-20+"px",top:g+"px",display:g>c-6&&g<c+d-
        6?"":"none"}))}))},renderTitle:function(){var a=this.padding,b=this.options.title,c=0;b.text&&(this.title||(this.title=this.chart.renderer.label(b.text,a-3,a-4,null,null,null,null,null,"legend-title").attr({zIndex:1}).css(b.style).add(this.group)),a=this.title.getBBox(),c=a.height,this.offsetWidth=a.width,this.contentGroup.attr({translateY:c}));this.titleHeight=c},renderItem:function(a){var b=this.chart,c=b.renderer,d=this.options,e="horizontal"===d.layout,f=this.symbolWidth,g=d.symbolPadding,h=this.itemStyle,
        k=this.itemHiddenStyle,r=this.padding,w=e?l(d.itemDistance,20):0,n=!d.rtl,m=d.width,s=d.itemMarginBottom||0,p=this.itemMarginTop,q=this.initialItemX,t=a.legendItem,v=a.series&&a.series.drawLegendSymbol?a.series:a,u=v.options,u=this.createCheckboxForItem&&u&&u.showCheckbox,z=d.useHTML;t||(a.legendGroup=c.g("legend-item").attr({zIndex:1}).add(this.scrollGroup),a.legendItem=t=c.text(d.labelFormat?xa(d.labelFormat,a):d.labelFormatter.call(a),n?f+g:-g,this.baseline||0,z).css(y(a.visible?h:k)).attr({align:n?
        "left":"right",zIndex:2}).add(a.legendGroup),this.baseline||(this.baseline=c.fontMetrics(h.fontSize,t).f+3+p,t.attr("y",this.baseline)),v.drawLegendSymbol(this,a),this.setItemEvents&&this.setItemEvents(a,t,z,h,k),this.colorizeItem(a,a.visible),u&&this.createCheckboxForItem(a));c=t.getBBox();f=a.checkboxOffset=d.itemWidth||a.legendItemWidth||f+g+c.width+w+(u?20:0);this.itemHeight=g=B(a.legendItemHeight||c.height);e&&this.itemX-q+f>(m||b.chartWidth-2*r-q-d.x)&&(this.itemX=q,this.itemY+=p+this.lastLineHeight+
        s,this.lastLineHeight=0);this.maxItemWidth=x(this.maxItemWidth,f);this.lastItemY=p+this.itemY+s;this.lastLineHeight=x(g,this.lastLineHeight);a._legendItemPos=[this.itemX,this.itemY];e?this.itemX+=f:(this.itemY+=p+g+s,this.lastLineHeight=g);this.offsetWidth=m||x((e?this.itemX-q-w:f)+r,this.offsetWidth)},getAllItems:function(){var a=[];v(this.chart.series,function(b){var c=b.options;l(c.showInLegend,n(c.linkedTo)?!1:A,!0)&&(a=a.concat(b.legendItems||("point"===c.legendType?b.data:b)))});return a},render:function(){var a=
        this,b=a.chart,c=b.renderer,d=a.group,e,f,g,h,k=a.box,r=a.options,l=a.padding,n=r.borderWidth,m=r.backgroundColor;a.itemX=a.initialItemX;a.itemY=a.initialItemY;a.offsetWidth=0;a.lastItemY=0;d||(a.group=d=c.g("legend").attr({zIndex:7}).add(),a.contentGroup=c.g().attr({zIndex:1}).add(d),a.scrollGroup=c.g().add(a.contentGroup));a.renderTitle();e=a.getAllItems();La(e,function(a,b){return(a.options&&a.options.legendIndex||0)-(b.options&&b.options.legendIndex||0)});r.reversed&&e.reverse();a.allItems=e;
        a.display=f=!!e.length;v(e,function(b){a.renderItem(b)});g=r.width||a.offsetWidth;h=a.lastItemY+a.lastLineHeight+a.titleHeight;h=a.handleOverflow(h);if(n||m)g+=l,h+=l,k?0<g&&0<h&&(k[k.isNew?"attr":"animate"](k.crisp({width:g,height:h})),k.isNew=!1):(a.box=k=c.rect(0,0,g,h,r.borderRadius,n||0).attr({stroke:r.borderColor,"stroke-width":n||0,fill:m||"none"}).add(d).shadow(r.shadow),k.isNew=!0),k[f?"show":"hide"]();a.legendWidth=g;a.legendHeight=h;v(e,function(b){a.positionItem(b)});f&&d.align(t({width:g,
            height:h},r),!0,"spacingBox");b.isResizing||this.positionCheckboxes()},handleOverflow:function(a){var b=this,c=this.chart,d=c.renderer,e=this.options,f=e.y,f=c.spacingBox.height+("top"===e.verticalAlign?-f:f)-this.padding,g=e.maxHeight,h,k=this.clipRect,r=e.navigation,n=l(r.animation,!0),m=r.arrowSize||12,p=this.nav,s=this.pages,q,t=this.allItems;"horizontal"===e.layout&&(f/=2);g&&(f=V(f,g));s.length=0;a>f&&!e.useHTML?(this.clipHeight=h=x(f-20-this.titleHeight-this.padding,0),this.currentPage=l(this.currentPage,
        1),this.fullHeight=a,v(t,function(a,b){var c=a._legendItemPos[1],d=B(a.legendItem.getBBox().height),e=s.length;if(!e||c-s[e-1]>h&&(q||c)!==s[e-1])s.push(q||c),e++;b===t.length-1&&c+d-s[e-1]>h&&s.push(c);c!==q&&(q=c)}),k||(k=b.clipRect=d.clipRect(0,this.padding,9999,0),b.contentGroup.clip(k)),k.attr({height:h}),p||(this.nav=p=d.g().attr({zIndex:1}).add(this.group),this.up=d.symbol("triangle",0,0,m,m).on("click",function(){b.scroll(-1,n)}).add(p),this.pager=d.text("",15,10).css(r.style).add(p),this.down=
        d.symbol("triangle-down",0,0,m,m).on("click",function(){b.scroll(1,n)}).add(p)),b.scroll(0),a=f):p&&(k.attr({height:c.chartHeight}),p.hide(),this.scrollGroup.attr({translateY:1}),this.clipHeight=0);return a},scroll:function(a,b){var c=this.pages,d=c.length,e=this.currentPage+a,f=this.clipHeight,g=this.options.navigation,h=g.activeColor,g=g.inactiveColor,k=this.pager,r=this.padding;e>d&&(e=d);0<e&&(b!==A&&(T=l(b,this.chart.animation)),this.nav.attr({translateX:r,translateY:f+this.padding+7+this.titleHeight,
        visibility:"visible"}),this.up.attr({fill:1===e?g:h}).css({cursor:1===e?"default":"pointer"}),k.attr({text:e+"/"+d}),this.down.attr({x:18+this.pager.getBBox().width,fill:e===d?g:h}).css({cursor:e===d?"default":"pointer"}),c=-c[e-1]+this.initialItemY,this.scrollGroup.animate({translateY:c}),this.currentPage=e,this.positionCheckboxes(c))}};var zb=ca.LegendSymbolMixin={drawRectangle:function(a,b){var c=a.options.symbolHeight||12;b.legendSymbol=this.chart.renderer.rect(0,a.baseline-5-c/2,a.symbolWidth,
        c,a.options.symbolRadius||0).attr({zIndex:3}).add(b.legendGroup)},drawLineMarker:function(a){var b=this.options,c=b.marker,d;d=a.symbolWidth;var e=this.chart.renderer,f=this.legendGroup;a=a.baseline-B(.3*e.fontMetrics(a.options.itemStyle.fontSize,this.legendItem).b);var g;b.lineWidth&&(g={"stroke-width":b.lineWidth},b.dashStyle&&(g.dashstyle=b.dashStyle),this.legendLine=e.path(["M",0,a,"L",d,a]).attr(g).add(f));c&&!1!==c.enabled&&(b=c.radius,this.legendSymbol=d=e.symbol(this.symbol,d/2-b,a-b,2*b,
            2*b).add(f),d.isMarker=!0)}};(/Trident\/7\.0/.test(ga)||Ha)&&bb(Za.prototype,"positionItem",function(a,b){var c=this,d=function(){b._legendItemPos&&a.call(c,b)};d();setTimeout(d)});Qa.prototype={init:function(a,b){var c,d=a.series;a.series=null;c=y(F,a);c.series=a.series=d;this.userOptions=a;d=c.chart;this.margin=this.splashArray("margin",d);this.spacing=this.splashArray("spacing",d);var e=d.events;this.bounds={h:{},v:{}};this.callback=b;this.isResizing=0;this.options=c;this.axes=[];this.series=[];
        this.hasCartesianSeries=d.showAxes;var f=this,g;f.index=ha.length;ha.push(f);mb++;!1!==d.reflow&&N(f,"load",function(){f.initReflow()});if(e)for(g in e)N(f,g,e[g]);f.xAxis=[];f.yAxis=[];f.animation=$?!1:l(d.animation,!0);f.pointCount=f.colorCounter=f.symbolCounter=0;f.firstRender()},initSeries:function(a){var b=this.options.chart;(b=ua[a.type||b.type||b.defaultSeriesType])||Q(17,!0);b=new b;b.init(this,a);return b},isInsidePlot:function(a,b,c){var d=c?b:a;a=c?a:b;return 0<=d&&d<=this.plotWidth&&0<=
        a&&a<=this.plotHeight},adjustTickAmounts:function(){!1!==this.options.chart.alignTicks&&v(this.axes,function(a){a.adjustTickAmount()});this.maxTicks=null},redraw:function(a){var b=this.axes,c=this.series,d=this.pointer,e=this.legend,f=this.isDirtyLegend,g,h,k=this.hasCartesianSeries,r=this.isDirtyBox,m=c.length,n=m,p=this.renderer,s=p.isHidden(),q=[];T=l(a,this.animation);s&&this.cloneRenderTo();for(this.layOutTitles();n--;)if(a=c[n],a.options.stacking&&(g=!0,a.isDirty)){h=!0;break}if(h)for(n=m;n--;)a=
        c[n],a.options.stacking&&(a.isDirty=!0);v(c,function(a){a.isDirty&&"point"===a.options.legendType&&(f=!0)});f&&e.options.enabled&&(e.render(),this.isDirtyLegend=!1);g&&this.getStacks();k&&(this.isResizing||(this.maxTicks=null,v(b,function(a){a.setScale()})),this.adjustTickAmounts());this.getMargins();k&&(v(b,function(a){a.isDirty&&(r=!0)}),v(b,function(a){a.isDirtyExtremes&&(a.isDirtyExtremes=!1,q.push(function(){O(a,"afterSetExtremes",t(a.eventArgs,a.getExtremes()));delete a.eventArgs}));(r||g)&&
    a.redraw()}));r&&this.drawChartBox();v(c,function(a){a.isDirty&&a.visible&&(!a.isCartesian||a.xAxis)&&a.redraw()});d&&d.reset(!0);p.draw();O(this,"redraw");s&&this.cloneRenderTo(!0);v(q,function(a){a.call()})},get:function(a){var b=this.axes,c=this.series,d,e;for(d=0;d<b.length;d++)if(b[d].options.id===a)return b[d];for(d=0;d<c.length;d++)if(c[d].options.id===a)return c[d];for(d=0;d<c.length;d++)for(e=c[d].points||[],b=0;b<e.length;b++)if(e[b].id===a)return e[b];return null},getAxes:function(){var a=
        this,b=this.options,c=b.xAxis=pa(b.xAxis||{}),b=b.yAxis=pa(b.yAxis||{});v(c,function(a,b){a.index=b;a.isX=!0});v(b,function(a,b){a.index=b});c=c.concat(b);v(c,function(b){new ma(a,b)});a.adjustTickAmounts()},getSelectedPoints:function(){var a=[];v(this.series,function(b){a=a.concat(Ta(b.points||[],function(a){return a.selected}))});return a},getSelectedSeries:function(){return Ta(this.series,function(a){return a.selected})},getStacks:function(){var a=this;v(a.yAxis,function(a){a.stacks&&a.hasVisibleSeries&&
    (a.oldStacks=a.stacks)});v(a.series,function(b){!b.options.stacking||!0!==b.visible&&!1!==a.options.chart.ignoreHiddenSeries||(b.stackKey=b.type+l(b.options.stack,""))})},setTitle:function(a,b,c){var d=this,e=d.options,f;f=e.title=y(e.title,a);e=e.subtitle=y(e.subtitle,b);v([["title",a,f],["subtitle",b,e]],function(a){var b=a[0],c=d[b],e=a[1];a=a[2];c&&e&&(d[b]=c=c.destroy());a&&a.text&&!c&&(d[b]=d.renderer.text(a.text,0,0,a.useHTML).attr({align:a.align,"class":"highcharts-"+b,zIndex:a.zIndex||4}).css(a.style).add())});
        d.layOutTitles(c)},layOutTitles:function(a){var b=0,c=this.title,d=this.subtitle,e=this.options,f=e.title,e=e.subtitle,g=this.renderer,h=this.spacingBox.width-44;c&&(c.css({width:(f.width||h)+"px"}).align(t({y:g.fontMetrics(f.style.fontSize,c).b-3},f),!1,"spacingBox"),f.floating||f.verticalAlign||(b=c.getBBox().height));d&&(d.css({width:(e.width||h)+"px"}).align(t({y:b+(f.margin-13)+g.fontMetrics(f.style.fontSize,d).b},e),!1,"spacingBox"),e.floating||e.verticalAlign||(b=na(b+d.getBBox().height)));
        c=this.titleOffset!==b;this.titleOffset=b;!this.isDirtyBox&&c&&(this.isDirtyBox=c,this.hasRendered&&l(a,!0)&&this.isDirtyBox&&this.redraw())},getChartSize:function(){var a=this.options.chart,b=a.width,a=a.height,c=this.renderToClone||this.renderTo;n(b)||(this.containerWidth=Ja(c,"width"));n(a)||(this.containerHeight=Ja(c,"height"));this.chartWidth=x(0,b||this.containerWidth||600);this.chartHeight=x(0,l(a,19<this.containerHeight?this.containerHeight:400))},cloneRenderTo:function(a){var b=this.renderToClone,
        c=this.container;a?b&&(this.renderTo.appendChild(c),Ba(b),delete this.renderToClone):(c&&c.parentNode===this.renderTo&&this.renderTo.removeChild(c),this.renderToClone=b=this.renderTo.cloneNode(0),R(b,{position:"absolute",top:"-9999px",display:"block"}),b.style.setProperty&&b.style.setProperty("display","block","important"),E.body.appendChild(b),c&&b.appendChild(c))},getContainer:function(){var a,b=this.options.chart,c,d,e;this.renderTo=a=b.renderTo;e="highcharts-"+Ra++;X(a)&&(this.renderTo=a=E.getElementById(a));
        a||Q(13,!0);c=u(m(a,"data-highcharts-chart"));!isNaN(c)&&ha[c]&&ha[c].hasRendered&&ha[c].destroy();m(a,"data-highcharts-chart",this.index);a.innerHTML="";b.skipClone||a.offsetWidth||this.cloneRenderTo();this.getChartSize();c=this.chartWidth;d=this.chartHeight;this.container=a=qa("div",{className:"highcharts-container"+(b.className?" "+b.className:""),id:e},t({position:"relative",overflow:"hidden",width:c+"px",height:d+"px",textAlign:"left",lineHeight:"normal",zIndex:0,"-webkit-tap-highlight-color":"rgba(0,0,0,0)"},
            b.style),this.renderToClone||a);this._cursor=a.style.cursor;this.renderer=b.forExport?new wa(a,c,d,b.style,!0):new wa(a,c,d,b.style);$&&this.renderer.create(this,a,c,d)},getMargins:function(){var a=this.spacing,b,c=this.legend,d=this.margin,e=this.options.legend,f=l(e.margin,20),g=e.x,h=e.y,k=e.align,r=e.verticalAlign,m=this.titleOffset;this.resetMargins();b=this.axisOffset;m&&!n(d[0])&&(this.plotTop=x(this.plotTop,m+this.options.title.margin+a[0]));c.display&&!e.floating&&("right"===k?n(d[1])||(this.marginRight=
        x(this.marginRight,c.legendWidth-g+f+a[1])):"left"===k?n(d[3])||(this.plotLeft=x(this.plotLeft,c.legendWidth+g+f+a[3])):"top"===r?n(d[0])||(this.plotTop=x(this.plotTop,c.legendHeight+h+f+a[0])):"bottom"!==r||n(d[2])||(this.marginBottom=x(this.marginBottom,c.legendHeight-h+f+a[2])));this.extraBottomMargin&&(this.marginBottom+=this.extraBottomMargin);this.extraTopMargin&&(this.plotTop+=this.extraTopMargin);this.hasCartesianSeries&&v(this.axes,function(a){a.getOffset()});n(d[3])||(this.plotLeft+=b[3]);
        n(d[0])||(this.plotTop+=b[0]);n(d[2])||(this.marginBottom+=b[2]);n(d[1])||(this.marginRight+=b[1]);this.setChartSize()},reflow:function(a){var b=this,c=b.options.chart,d=b.renderTo,e=c.width||Ja(d,"width"),f=c.height||Ja(d,"height"),c=a?a.target:J,d=function(){b.container&&(b.setSize(e,f,!1),b.hasUserSize=null)};if(!b.hasUserSize&&e&&f&&(c===J||c===E)){if(e!==b.containerWidth||f!==b.containerHeight)clearTimeout(b.reflowTimeout),a?b.reflowTimeout=setTimeout(d,100):d();b.containerWidth=e;b.containerHeight=
        f}},initReflow:function(){var a=this,b=function(b){a.reflow(b)};N(J,"resize",b);N(a,"destroy",function(){U(J,"resize",b)})},setSize:function(a,b,c){var d=this,e,f,g;d.isResizing+=1;g=function(){d&&O(d,"endResize",null,function(){d.isResizing-=1})};T=l(c,d.animation);d.oldChartHeight=d.chartHeight;d.oldChartWidth=d.chartWidth;n(a)&&(d.chartWidth=e=x(0,B(a)),d.hasUserSize=!!e);n(b)&&(d.chartHeight=f=x(0,B(b)));(T?ob:R)(d.container,{width:e+"px",height:f+"px"},T);d.setChartSize(!0);d.renderer.setSize(e,
        f,c);d.maxTicks=null;v(d.axes,function(a){a.isDirty=!0;a.setScale()});v(d.series,function(a){a.isDirty=!0});d.isDirtyLegend=!0;d.isDirtyBox=!0;d.layOutTitles();d.getMargins();d.redraw(c);d.oldChartHeight=null;O(d,"resize");!1===T?g():setTimeout(g,T&&T.duration||500)},setChartSize:function(a){var b=this.inverted,c=this.renderer,d=this.chartWidth,e=this.chartHeight,f=this.options.chart,g=this.spacing,h=this.clipOffset,k,r,l,m;this.plotLeft=k=B(this.plotLeft);this.plotTop=r=B(this.plotTop);this.plotWidth=
        l=x(0,B(d-k-this.marginRight));this.plotHeight=m=x(0,B(e-r-this.marginBottom));this.plotSizeX=b?m:l;this.plotSizeY=b?l:m;this.plotBorderWidth=f.plotBorderWidth||0;this.spacingBox=c.spacingBox={x:g[3],y:g[0],width:d-g[3]-g[1],height:e-g[0]-g[2]};this.plotBox=c.plotBox={x:k,y:r,width:l,height:m};d=2*I(this.plotBorderWidth/2);b=na(x(d,h[3])/2);c=na(x(d,h[0])/2);this.clipBox={x:b,y:c,width:I(this.plotSizeX-x(d,h[1])/2-b),height:x(0,I(this.plotSizeY-x(d,h[2])/2-c))};a||v(this.axes,function(a){a.setAxisSize();
        a.setAxisTranslation()})},resetMargins:function(){var a=this.spacing,b=this.margin;this.plotTop=l(b[0],a[0]);this.marginRight=l(b[1],a[1]);this.marginBottom=l(b[2],a[2]);this.plotLeft=l(b[3],a[3]);this.axisOffset=[0,0,0,0];this.clipOffset=[0,0,0,0]},drawChartBox:function(){var a=this.options.chart,b=this.renderer,c=this.chartWidth,d=this.chartHeight,e=this.chartBackground,f=this.plotBackground,g=this.plotBorder,h=this.plotBGImage,k=a.borderWidth||0,l=a.backgroundColor,m=a.plotBackgroundColor,n=a.plotBackgroundImage,
        p=a.plotBorderWidth||0,s,q=this.plotLeft,t=this.plotTop,v=this.plotWidth,u=this.plotHeight,x=this.plotBox,z=this.clipRect,y=this.clipBox;s=k+(a.shadow?8:0);if(k||l)e?e.animate(e.crisp({width:c-s,height:d-s})):(e={fill:l||"none"},k&&(e.stroke=a.borderColor,e["stroke-width"]=k),this.chartBackground=b.rect(s/2,s/2,c-s,d-s,a.borderRadius,k).attr(e).addClass("highcharts-background").add().shadow(a.shadow));m&&(f?f.animate(x):this.plotBackground=b.rect(q,t,v,u,0).attr({fill:m}).add().shadow(a.plotShadow));
        n&&(h?h.animate(x):this.plotBGImage=b.image(n,q,t,v,u).add());z?z.animate({width:y.width,height:y.height}):this.clipRect=b.clipRect(y);p&&(g?g.animate(g.crisp({x:q,y:t,width:v,height:u,strokeWidth:-p})):this.plotBorder=b.rect(q,t,v,u,0,-p).attr({stroke:a.plotBorderColor,"stroke-width":p,fill:"none",zIndex:1}).add());this.isDirtyBox=!1},propFromSeries:function(){var a=this,b=a.options.chart,c,d=a.options.series,e,f;v(["inverted","angular","polar"],function(g){c=ua[b.type||b.defaultSeriesType];f=a[g]||
        b[g]||c&&c.prototype[g];for(e=d&&d.length;!f&&e--;)(c=ua[d[e].type])&&c.prototype[g]&&(f=!0);a[g]=f})},linkSeries:function(){var a=this,b=a.series;v(b,function(a){a.linkedSeries.length=0});v(b,function(b){var d=b.options.linkedTo;X(d)&&(d=":previous"===d?a.series[b.index-1]:a.get(d))&&(d.linkedSeries.push(b),b.linkedParent=d)})},renderSeries:function(){v(this.series,function(a){a.translate();a.setTooltipPoints&&a.setTooltipPoints();a.render()})},renderLabels:function(){var a=this,b=a.options.labels;
        b.items&&v(b.items,function(c){var d=t(b.style,c.style),e=u(d.left)+a.plotLeft,f=u(d.top)+a.plotTop+12;delete d.left;delete d.top;a.renderer.text(c.html,e,f).attr({zIndex:2}).css(d).add()})},render:function(){var a=this.axes,b=this.renderer,c=this.options;this.setTitle();this.legend=new Za(this,c.legend);this.getStacks();v(a,function(a){a.setScale()});this.getMargins();this.maxTicks=null;v(a,function(a){a.setTickPositions(!0);a.setMaxTicks()});this.adjustTickAmounts();this.getMargins();this.drawChartBox();
        this.hasCartesianSeries&&v(a,function(a){a.render()});this.seriesGroup||(this.seriesGroup=b.g("series-group").attr({zIndex:3}).add());this.renderSeries();this.renderLabels();this.showCredits(c.credits);this.hasRendered=!0},showCredits:function(a){a.enabled&&!this.credits&&(this.credits=this.renderer.text(a.text,0,0).on("click",function(){a.href&&(location.href=a.href)}).attr({align:a.position.align,zIndex:8}).css(a.style).add().align(a.position))},destroy:function(){var a=this,b=a.axes,c=a.series,
        d=a.container,e,f=d&&d.parentNode;O(a,"destroy");ha[a.index]=A;mb--;a.renderTo.removeAttribute("data-highcharts-chart");U(a);for(e=b.length;e--;)b[e]=b[e].destroy();for(e=c.length;e--;)c[e]=c[e].destroy();v("title subtitle chartBackground plotBackground plotBGImage plotBorder seriesGroup clipRect credits pointer scroller rangeSelector legend resetZoomButton tooltip renderer".split(" "),function(b){var c=a[b];c&&c.destroy&&(a[b]=c.destroy())});d&&(d.innerHTML="",U(d),f&&Ba(d));for(e in a)delete a[e]},
        isReadyToRender:function(){var a=this;return!S&&J==J.top&&"complete"!==E.readyState||$&&!J.canvg?($?CanVGController.push(function(){a.firstRender()},a.options.global.canvasToolsURL):E.attachEvent("onreadystatechange",function(){E.detachEvent("onreadystatechange",a.firstRender);"complete"===E.readyState&&a.firstRender()}),!1):!0},firstRender:function(){var a=this,b=a.options,c=a.callback;a.isReadyToRender()&&(a.getContainer(),O(a,"init"),a.resetMargins(),a.setChartSize(),a.propFromSeries(),a.getAxes(),
            v(b.series||[],function(b){a.initSeries(b)}),a.linkSeries(),O(a,"beforeRender"),ca.Pointer&&(a.pointer=new Pointer(a,b)),a.render(),a.renderer.draw(),c&&c.apply(a,[a]),v(a.callbacks,function(b){b.apply(a,[a])}),a.cloneRenderTo(!0),O(a,"load"))},splashArray:function(a,b){var c=b[a],c=C(c)?c:[c,c,c,c];return[l(b[a+"Top"],c[0]),l(b[a+"Right"],c[1]),l(b[a+"Bottom"],c[2]),l(b[a+"Left"],c[3])]}};Qa.prototype.callbacks=[];var Ka=function(){};Ka.prototype={init:function(a,b,c){this.series=a;this.applyOptions(b,
        c);this.pointAttr={};a.options.colorByPoint&&(b=a.options.colors||a.chart.options.colors,this.color=this.color||b[a.colorCounter++],a.colorCounter===b.length&&(a.colorCounter=0));a.chart.pointCount++;return this},applyOptions:function(a,b){var c=this.series,d=c.options.pointValKey||c.pointValKey;a=Ka.prototype.optionsToObject.call(this,a);t(this,a);this.options=this.options?t(this.options,a):a;d&&(this.y=this[d]);this.x===A&&c&&(this.x=b===A?c.autoIncrement():b);return this},optionsToObject:function(a){var b=
    {},c=this.series,d=c.pointArrayMap||["y"],e=d.length,f=0,g=0;if("number"===typeof a||null===a)b[d[0]]=a;else if(ba(a))for(a.length>e&&(c=typeof a[0],"string"===c?b.name=a[0]:"number"===c&&(b.x=a[0]),f++);g<e;)b[d[g++]]=a[f++];else"object"===typeof a&&(b=a,a.dataLabels&&(c._hasPointLabels=!0),a.marker&&(c._hasPointMarkers=!0));return b},destroy:function(){var a=this.series.chart,b=a.hoverPoints,c;a.pointCount--;b&&(this.setState(),q(b,this),b.length||(a.hoverPoints=null));if(this===a.hoverPoint)this.onMouseOut();
        if(this.graphic||this.dataLabel)U(this),this.destroyElements();this.legendItem&&a.legend.destroyItem(this);for(c in this)this[c]=null},destroyElements:function(){for(var a="graphic dataLabel dataLabelUpper group connector shadowGroup".split(" "),b,c=6;c--;)b=a[c],this[b]&&(this[b]=this[b].destroy())},getLabelConfig:function(){return{x:this.category,y:this.y,key:this.name||this.category,series:this.series,point:this,percentage:this.percentage,total:this.total||this.stackTotal}},tooltipFormatter:function(a){var b=
        this.series,c=b.tooltipOptions,d=l(c.valueDecimals,""),e=c.valuePrefix||"",f=c.valueSuffix||"";v(b.pointArrayMap||["y"],function(b){b="{point."+b;if(e||f)a=a.replace(b+"}",e+b+"}"+f);a=a.replace(b+"}",b+":,."+d+"f}")});return xa(a,{point:this,series:this.series})},firePointEvent:function(a,b,c){var d=this,e=this.series.options;(e.point.events[a]||d.options&&d.options.events&&d.options.events[a])&&this.importEvents();"click"===a&&e.allowPointSelect&&(c=function(a){d.select(null,a.ctrlKey||a.metaKey||
        a.shiftKey)});O(this,a,b,c)}};var $a=function(){};$a.prototype={isCartesian:!0,type:"line",pointClass:Ka,sorted:!0,requireSorting:!0,pointAttrToOptions:{stroke:"lineColor","stroke-width":"lineWidth",fill:"fillColor",r:"radius"},axisTypes:["xAxis","yAxis"],colorCounter:0,parallelArrays:["x","y"],init:function(a,b){var c=this,d,e,f=a.series,g=function(a,b){return l(a.options.index,a._i)-l(b.options.index,b._i)};c.chart=a;c.options=b=c.setOptions(b);c.linkedSeries=[];c.bindAxes();t(c,{name:b.name,state:"",
        pointAttr:{},visible:!1!==b.visible,selected:!0===b.selected});$&&(b.animation=!1);e=b.events;for(d in e)N(c,d,e[d]);if(e&&e.click||b.point&&b.point.events&&b.point.events.click||b.allowPointSelect)a.runTrackerClick=!0;c.getColor();c.getSymbol();v(c.parallelArrays,function(a){c[a+"Data"]=[]});c.setData(b.data,!1);c.isCartesian&&(a.hasCartesianSeries=!0);f.push(c);c._i=f.length-1;La(f,g);this.yAxis&&La(this.yAxis.series,g);v(f,function(a,b){a.index=b;a.name=a.name||"Series "+(b+1)})},bindAxes:function(){var a=
        this,b=a.options,c=a.chart,d;v(a.axisTypes||[],function(e){v(c[e],function(c){d=c.options;if(b[e]===d.index||b[e]!==A&&b[e]===d.id||b[e]===A&&0===d.index)c.series.push(a),a[e]=c,c.isDirty=!0});a[e]||a.optionalAxis===e||Q(18,!0)})},updateParallelArrays:function(a,b){var c=a.series,d=arguments;v(c.parallelArrays,"number"===typeof b?function(d){var f="y"===d&&c.toYData?c.toYData(a):a[d];c[d+"Data"][b]=f}:function(a){Array.prototype[b].apply(c[a+"Data"],Array.prototype.slice.call(d,2))})},autoIncrement:function(){var a=
        this.options,b=this.xIncrement,b=l(b,a.pointStart,0);this.pointInterval=l(this.pointInterval,a.pointInterval,1);this.xIncrement=b+this.pointInterval;return b},getSegments:function(){var a=-1,b=[],c,d=this.points,e=d.length;if(e)if(this.options.connectNulls){for(c=e;c--;)null===d[c].y&&d.splice(c,1);d.length&&(b=[d])}else v(d,function(c,g){null===c.y?(g>a+1&&b.push(d.slice(a+1,g)),a=g):g===e-1&&b.push(d.slice(a+1,g+1))});this.segments=b},setOptions:function(a){var b=this.chart,c=b.options.plotOptions,
        b=b.userOptions||{},d=b.plotOptions||{},e=c[this.type];this.userOptions=a;c=y(e,c.series,a);this.tooltipOptions=y(F.tooltip,F.plotOptions[this.type].tooltip,b.tooltip,d.series&&d.series.tooltip,d[this.type]&&d[this.type].tooltip,a.tooltip);null===e.marker&&delete c.marker;return c},getCyclic:function(a,b,c){var d=this.userOptions,e="_"+a+"Index",f=a+"Counter";b||(n(d[e])?b=d[e]:(d[e]=b=this.chart[f]%c.length,this.chart[f]+=1),b=c[b]);this[a]=b},getColor:function(){this.options.colorByPoint||this.getCyclic("color",
            this.options.color||Wa[this.type].color,this.chart.options.colors)},getSymbol:function(){var a=this.options.marker;this.getCyclic("symbol",a.symbol,this.chart.options.symbols);/^url/.test(this.symbol)&&(a.radius=0)},drawLegendSymbol:zb.drawLineMarker,setData:function(a,b,c,d){var e=this,f=e.points,g=f&&f.length||0,h,k=e.options,r=e.chart,m=null,n=e.xAxis,p=n&&!!n.categories,s=e.tooltipPoints,q=k.turboThreshold,t=this.xData,u=this.yData,x=(h=e.pointArrayMap)&&h.length;a=a||[];h=a.length;b=l(b,!0);
        if(!1===d||!h||g!==h||e.cropped||e.hasGroupedData){e.xIncrement=null;e.pointRange=p?1:k.pointRange;e.colorCounter=0;v(this.parallelArrays,function(a){e[a+"Data"].length=0});if(q&&h>q){for(c=0;null===m&&c<h;)m=a[c],c++;if(P(m)){p=l(k.pointStart,0);k=l(k.pointInterval,1);for(c=0;c<h;c++)t[c]=p,u[c]=a[c],p+=k;e.xIncrement=p}else if(ba(m))if(x)for(c=0;c<h;c++)k=a[c],t[c]=k[0],u[c]=k.slice(1,x+1);else for(c=0;c<h;c++)k=a[c],t[c]=k[0],u[c]=k[1];else Q(12)}else for(c=0;c<h;c++)a[c]!==A&&(k={series:e},e.pointClass.prototype.applyOptions.apply(k,
            [a[c]]),e.updateParallelArrays(k,c),p&&k.name&&(n.names[k.x]=k.name));X(u[0])&&Q(14,!0);e.data=[];e.options.data=a;for(c=g;c--;)f[c]&&f[c].destroy&&f[c].destroy();s&&(s.length=0);n&&(n.minRange=n.userMinRange);e.isDirty=e.isDirtyData=r.isDirtyBox=!0;c=!1}else v(a,function(a,b){f[b].update(a,!1,null,!1)});b&&r.redraw(c)},processData:function(a){var b=this.xData,c=this.yData,d=b.length,e;e=0;var f,g,h=this.xAxis,k,l=this.options;k=l.cropThreshold;var m=0,n=this.isCartesian,p,s;if(n&&!this.isDirty&&
        !h.isDirty&&!this.yAxis.isDirty&&!a)return!1;h&&(p=h.getExtremes(),s=p.min,p=p.max);if(n&&this.sorted&&(!k||d>k||this.forceCrop))if(b[d-1]<s||b[0]>p)b=[],c=[];else if(b[0]<s||b[d-1]>p)e=this.cropData(this.xData,this.yData,s,p),b=e.xData,c=e.yData,e=e.start,f=!0,m=b.length;for(k=b.length-1;0<=k;k--)d=b[k]-b[k-1],!f&&b[k]>s&&b[k]<p&&m++,0<d&&(g===A||d<g)?g=d:0>d&&this.requireSorting&&Q(15);this.cropped=f;this.cropStart=e;this.processedXData=b;this.processedYData=c;this.activePointCount=m;null===l.pointRange&&
    (this.pointRange=g||1);this.closestPointRange=g},cropData:function(a,b,c,d){var e=a.length,f=0,g=e,h=l(this.cropShoulder,1),k;for(k=0;k<e;k++)if(a[k]>=c){f=x(0,k-h);break}for(;k<e;k++)if(a[k]>d){g=k+h;break}return{xData:a.slice(f,g),yData:b.slice(f,g),start:f,end:g}},generatePoints:function(){var a=this.options.data,b=this.data,c,d=this.processedXData,e=this.processedYData,f=this.pointClass,g=d.length,h=this.cropStart||0,k,l=this.hasGroupedData,m,n=[],p;b||l||(b=[],b.length=a.length,b=this.data=b);
        for(p=0;p<g;p++)k=h+p,l?n[p]=(new f).init(this,[d[p]].concat(pa(e[p]))):(b[k]?m=b[k]:a[k]!==A&&(b[k]=m=(new f).init(this,a[k],d[p])),n[p]=m),n[p].index=k;if(b&&(g!==(c=b.length)||l))for(p=0;p<c;p++)p!==h||l||(p+=g),b[p]&&(b[p].destroyElements(),b[p].plotX=A);this.data=b;this.points=n},getExtremes:function(a){var b=this.yAxis,c=this.processedXData,d,e=[],f=0;d=this.xAxis.getExtremes();var g=d.min,h=d.max,k,m,n,p;a=a||this.stackedYData||this.processedYData;d=a.length;for(p=0;p<d;p++)if(m=c[p],n=a[p],
        k=null!==n&&n!==A&&(!b.isLog||n.length||0<n),m=this.getExtremesFromAll||this.cropped||(c[p+1]||m)>=g&&(c[p-1]||m)<=h,k&&m)if(k=n.length)for(;k--;)null!==n[k]&&(e[f++]=n[k]);else e[f++]=n;this.dataMin=l(void 0,za(e));this.dataMax=l(void 0,ra(e))},translate:function(){this.processedXData||this.processData();this.generatePoints();for(var a=this.options,b=a.stacking,c=this.xAxis,d=c.categories,e=this.yAxis,f=this.points,g=f.length,h=!!this.modifyValue,k=a.pointPlacement,m="between"===k||P(k),p=a.threshold,
                                                                                                                                                                                                                                                                                                                                                         a=0;a<g;a++){var q=f[a],t=q.x,s=q.y,v=q.low,u=b&&e.stacks[(this.negStacks&&s<p?"-":"")+this.stackKey];e.isLog&&0>=s&&(q.y=s=null,Q(10));q.plotX=c.translate(t,0,0,0,1,k,"flags"===this.type);b&&this.visible&&u&&u[t]&&(u=u[t],s=u.points[this.index+","+a],v=s[0],s=s[1],0===v&&(v=l(p,e.min)),e.isLog&&0>=v&&(v=null),q.total=q.stackTotal=u.total,q.percentage=u.total&&q.y/u.total*100,q.stackY=s,u.setOffset(this.pointXOffset||0,this.barW||0));q.yBottom=n(v)?e.translate(v,0,1,0,1):null;h&&(s=this.modifyValue(s,
        q));q.plotY="number"===typeof s&&Infinity!==s?e.translate(s,0,1,0,1):A;q.clientX=m?c.translate(t,0,0,0,1):q.plotX;q.negative=q.y<(p||0);q.category=d&&d[q.x]!==A?d[q.x]:q.x}this.getSegments()},animate:function(a){var b=this.chart,c=b.renderer,d;d=this.options.animation;var e=this.clipBox||b.clipBox,f=b.inverted,g;d&&!C(d)&&(d=Wa[this.type].animation);g=["_sharedClip",d.duration,d.easing,e.height].join();a?(a=b[g],d=b[g+"m"],a||(b[g]=a=c.clipRect(t(e,{width:0})),b[g+"m"]=d=c.clipRect(-99,f?-b.plotLeft:
        -b.plotTop,99,f?b.chartWidth:b.chartHeight)),this.group.clip(a),this.markerGroup.clip(d),this.sharedClipKey=g):((a=b[g])&&a.animate({width:b.plotSizeX},d),b[g+"m"]&&b[g+"m"].animate({width:b.plotSizeX+99},d),this.animate=null)},afterAnimate:function(){var a=this.chart,b=this.sharedClipKey,c=this.group,d=this.clipBox;c&&!1!==this.options.clip&&(b&&d||c.clip(d?a.renderer.clipRect(d):a.clipRect),this.markerGroup.clip());O(this,"afterAnimate");setTimeout(function(){b&&a[b]&&(d||(a[b]=a[b].destroy()),
        a[b+"m"]&&(a[b+"m"]=a[b+"m"].destroy()))},100)},drawPoints:function(){var a,b=this.points,c=this.chart,d,e,f,g,h,k,m,n,p=this.options.marker,q=this.pointAttr[""],s,v,u,x=this.markerGroup,y=l(p.enabled,!this.requireSorting||this.activePointCount<.5*this.xAxis.len/p.radius);if(!1!==p.enabled||this._hasPointMarkers)for(f=b.length;f--;)g=b[f],d=I(g.plotX),e=g.plotY,n=g.graphic,s=g.marker||{},v=!!g.marker,a=y&&s.enabled===A||s.enabled,u=c.isInsidePlot(B(d),e,c.inverted),a&&e!==A&&!isNaN(e)&&null!==g.y?
        (a=g.pointAttr[g.selected?"select":""]||q,h=a.r,k=l(s.symbol,this.symbol),m=0===k.indexOf("url"),n?n[u?"show":"hide"](!0).animate(t({x:d-h,y:e-h},n.symbolName?{width:2*h,height:2*h}:{})):u&&(0<h||m)&&(g.graphic=c.renderer.symbol(k,d-h,e-h,2*h,2*h,v?s:p).attr(a).add(x))):n&&(g.graphic=n.destroy())},convertAttribs:function(a,b,c,d){var e=this.pointAttrToOptions,f,g,h={};a=a||{};b=b||{};c=c||{};d=d||{};for(f in e)g=e[f],h[f]=l(a[g],b[f],c[f],d[f]);return h},getAttribs:function(){var a=this,b=a.options,
        c=Wa[a.type].marker?b.marker:b,d=c.states,e=d.hover,f,g=a.color;f={stroke:g,fill:g};var h=a.points||[],k,l=[],m,p=a.pointAttrToOptions;m=a.hasPointSpecificOptions;var q=b.negativeColor,s=c.lineColor,u=c.fillColor;k=b.turboThreshold;var x;b.marker?(e.radius=e.radius||c.radius+e.radiusPlus,e.lineWidth=e.lineWidth||c.lineWidth+e.lineWidthPlus):e.color=e.color||va(e.color||g).brighten(e.brightness).get();l[""]=a.convertAttribs(c,f);v(["hover","select"],function(b){l[b]=a.convertAttribs(d[b],l[""])});
        a.pointAttr=l;g=h.length;if(!k||g<k||m)for(;g--;){k=h[g];(c=k.options&&k.options.marker||k.options)&&!1===c.enabled&&(c.radius=0);k.negative&&q&&(k.color=k.fillColor=q);m=b.colorByPoint||k.color;if(k.options)for(x in p)n(c[p[x]])&&(m=!0);m?(c=c||{},m=[],d=c.states||{},f=d.hover=d.hover||{},b.marker||(f.color=f.color||!k.options.color&&e.color||va(k.color).brighten(f.brightness||e.brightness).get()),f={color:k.color},u||(f.fillColor=k.color),s||(f.lineColor=k.color),m[""]=a.convertAttribs(t(f,c),l[""]),
            m.hover=a.convertAttribs(d.hover,l.hover,m[""]),m.select=a.convertAttribs(d.select,l.select,m[""])):m=l;k.pointAttr=m}},destroy:function(){var a=this,b=a.chart,c=/AppleWebKit\/533/.test(ga),d,e,f=a.data||[],g,h,k;O(a,"destroy");U(a);v(a.axisTypes||[],function(b){if(k=a[b])q(k.series,a),k.isDirty=k.forceRedraw=!0});a.legendItem&&a.chart.legend.destroyItem(a);for(e=f.length;e--;)(g=f[e])&&g.destroy&&g.destroy();a.points=null;clearTimeout(a.animationTimeout);v("area graph dataLabelsGroup group markerGroup tracker graphNeg areaNeg posClip negClip".split(" "),
        function(b){a[b]&&(d=c&&"group"===b?"hide":"destroy",a[b][d]())});b.hoverSeries===a&&(b.hoverSeries=null);q(b.series,a);for(h in a)delete a[h]},getSegmentPath:function(a){var b=this,c=[],d=b.options.step;v(a,function(e,f){var g=e.plotX,h=e.plotY,k;b.getPointSpline?c.push.apply(c,b.getPointSpline(a,e,f)):(c.push(f?"L":"M"),d&&f&&(k=a[f-1],"right"===d?c.push(k.plotX,h):"center"===d?c.push((k.plotX+g)/2,k.plotY,(k.plotX+g)/2,h):c.push(g,k.plotY)),c.push(e.plotX,e.plotY))});return c},getGraphPath:function(){var a=
        this,b=[],c,d=[];v(a.segments,function(e){c=a.getSegmentPath(e);1<e.length?b=b.concat(c):d.push(e[0])});a.singlePoints=d;return a.graphPath=b},drawGraph:function(){var a=this,b=this.options,c=[["graph",b.lineColor||this.color]],d=b.lineWidth,e=b.dashStyle,f="square"!==b.linecap,g=this.getGraphPath(),h=b.negativeColor;h&&c.push(["graphNeg",h]);v(c,function(c,h){var l=c[0],m=a[l];m?(Ua(m),m.animate({d:g})):d&&g.length&&(m={stroke:c[1],"stroke-width":d,fill:"none",zIndex:1},e?m.dashstyle=e:f&&(m["stroke-linecap"]=
        m["stroke-linejoin"]="round"),a[l]=a.chart.renderer.path(g).attr(m).add(a.group).shadow(!h&&b.shadow))})},clipNeg:function(){var a=this.options,b=this.chart,c=b.renderer,d=a.negativeColor||a.negativeFillColor,e,f=this.graph,g=this.area,h=this.posClip,k=this.negClip;e=b.chartWidth;var m=b.chartHeight,l=x(e,m),n=this.yAxis;d&&(f||g)&&(d=B(n.toPixels(a.threshold||0,!0)),0>d&&(l-=d),a={x:0,y:0,width:l,height:d},l={x:0,y:d,width:l,height:l},b.inverted&&(a.height=l.y=b.plotWidth-d,c.isVML&&(a={x:b.plotWidth-
        d-b.plotLeft,y:0,width:e,height:m},l={x:d+b.plotLeft-e,y:0,width:b.plotLeft+d,height:e})),n.reversed?(b=l,e=a):(b=a,e=l),h?(h.animate(b),k.animate(e)):(this.posClip=h=c.clipRect(b),this.negClip=k=c.clipRect(e),f&&this.graphNeg&&(f.clip(h),this.graphNeg.clip(k)),g&&(g.clip(h),this.areaNeg.clip(k))))},invertGroups:function(){function a(){var a={width:b.yAxis.len,height:b.xAxis.len};v(["group","markerGroup"],function(c){b[c]&&b[c].attr(a).invert()})}var b=this,c=b.chart;b.xAxis&&(N(c,"resize",a),N(b,
        "destroy",function(){U(c,"resize",a)}),a(),b.invertGroups=a)},plotGroup:function(a,b,c,d,e){var f=this[a],g=!f;g&&(this[a]=f=this.chart.renderer.g(b).attr({visibility:c,zIndex:d||.1}).add(e));f[g?"attr":"animate"](this.getPlotBox());return f},getPlotBox:function(){var a=this.chart,b=this.xAxis,c=this.yAxis;a.inverted&&(b=c,c=this.xAxis);return{translateX:b?b.left:a.plotLeft,translateY:c?c.top:a.plotTop,scaleX:1,scaleY:1}},render:function(){var a=this,b=a.chart,c,d=a.options,e=(c=d.animation)&&!!a.animate&&
        b.renderer.isSVG&&l(c.duration,500)||0,f=a.visible?"visible":"hidden",g=d.zIndex,h=a.hasRendered,k=b.seriesGroup;c=a.plotGroup("group","series",f,g,k);a.markerGroup=a.plotGroup("markerGroup","markers",f,g,k);e&&a.animate(!0);a.getAttribs();c.inverted=a.isCartesian?b.inverted:!1;a.drawGraph&&(a.drawGraph(),a.clipNeg());v(a.points,function(a){a.redraw&&a.redraw()});a.drawDataLabels&&a.drawDataLabels();a.visible&&a.drawPoints();a.drawTracker&&!1!==a.options.enableMouseTracking&&a.drawTracker();b.inverted&&
    a.invertGroups();!1===d.clip||a.sharedClipKey||h||c.clip(b.clipRect);e&&a.animate();h||(e?a.animationTimeout=setTimeout(function(){a.afterAnimate()},e):a.afterAnimate());a.isDirty=a.isDirtyData=!1;a.hasRendered=!0},redraw:function(){var a=this.chart,b=this.isDirtyData,c=this.group,d=this.xAxis,e=this.yAxis;c&&(a.inverted&&c.attr({width:a.plotWidth,height:a.plotHeight}),c.animate({translateX:l(d&&d.left,a.plotLeft),translateY:l(e&&e.top,a.plotTop)}));this.translate();this.setTooltipPoints&&this.setTooltipPoints(!0);
        this.render();b&&O(this,"updatedData")}};var Ab=ab($a);ua.line=Ab;t(ca,{Axis:ma,Chart:Qa,Color:va,Point:Ka,Tick:la,Renderer:wa,Series:$a,SVGElement:L,SVGRenderer:wa,arrayMin:za,arrayMax:ra,charts:ha,dateFormat:ya,format:xa,pathAnim:Sa,getOptions:function(){return F},hasBidiBug:tb,isTouchDevice:kb,numberFormat:aa,seriesTypes:ua,setOptions:function(a){F=y(!0,F,a);db();return F},addEvent:N,removeEvent:U,createElement:qa,discardElement:Ba,css:R,each:v,extend:t,map:nb,merge:y,pick:l,splat:pa,extendClass:ab,
        pInt:u,wrap:bb,svg:S,canvas:$,vml:!S&&!$,product:"Highcharts 4.0.4",version:"/Highstock 2.0.4"})})();